export const dataKingMaker = [
  {
    image: require("../../assets/images/3d-game/list-3d-game/kingmaster/thai-hi-lo.jpg"),
    title: "Thai Hi Lo",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/kingmaster/belangkai.jpg"),
    title: "Belangkai 2",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/kingmaster/daragon-tiger-2.jpg"),
    title: "Dragon Tiger 2",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/kingmaster/fish-prawn-crab.jpg"),
    title: "Fish Prawn Crab 2",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/kingmaster/bau-cua.jpg"),
    title: "Viet Fish Prawn Crab",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/kingmaster/sic-bo.jpg"),
    title: "Sic Bo",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/kingmaster/xoc-dia.jpg"),
    title: "Xoc Dia",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/kingmaster/tai-xiu.jpg"),
    title: "Tai Xiu",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/kingmaster/keno.jpg"),
    title: "Keno",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/kingmaster/thai-fish-prawn-crab.jpg"),
    title: "Thai Fish Prawn Crab",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/kingmaster/classic-fantan.jpg"),
    title: "Classic Fan Tan",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/kingmaster/number-matka.jpg"),
    title: "Number Matka",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/kingmaster/plinko.jpg"),
    title: "Plinko",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
];

export const dataGamePlay = [
  {
    image: require("../../assets/images/3d-game/list-3d-game/gameplay/fish-prawn-crab.jpg"),
    title: "Fish Prawn Crab",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/gameplay/the-ladder.jpg"),
    title: "The Ladder",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/gameplay/lucky-derby.jpg"),
    title: "Lucky Derby",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/gameplay/pk-10.jpg"),
    title: "PK10",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/gameplay/rock-paper-scissors.jpg"),
    title: "Rock Paper Scissors",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/gameplay/tai-xiu.jpg"),
    title: "Tai Xiu",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/gameplay/thai-hi-lo.jpg"),
    title: "Thai Hi Lo",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/gameplay/thor.jpg"),
    title: "Thor",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/gameplay/xoc-dia.jpg"),
    title: "Xoc Dia",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/gameplay/fa-fa-roulette.jpg"),
    title: "Fa Fa Roulette",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
];

export const dataV8Poker = [
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/killer-13.jpg"),
    title: "Killer 13",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/fight-the-landlord.jpg"),
    title: "Fight The Landlord",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/fish-shrimp-crab.jpg"),
    title: "Fish-Shrimp-Crab",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/xoc-dia.jpg"),
    title: "Xoc Dia",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/hundred-sic-bo.jpg"),
    title: "Hundred Sic Bo",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/three-toy.jpg"),
    title: "Three Toy",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/texas-holdem-poker.jpg"),
    title: "Texas Holdem Poker",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/fan-tan.jpg"),
    title: "Fan Tan",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/four-cards-bull.jpg"),
    title: "Four Cards Bull",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/baccarat.jpg"),
    title: "Baccarat",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/six-cards.jpg"),
    title: "Six Cards",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/black-jack.jpg"),
    title: "Black Jack",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/three-cards.jpg"),
    title: "Three Cards",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/bull-bull.jpg"),
    title: "Bull-Bull",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/red-black-war.jpg"),
    title: "Red-Black War",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/see-cards-bull.jpg"),
    title: "See Card Bull",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/v8poker/hundreds-people-of-bull.jpg"),
    title: "Hundred People of Bull",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
];

export const dataMiniTed = [
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/beat-bullfight.jpg"),
    title: "Beat Bullfight",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/mutual-bullfight.jpg"),
    title: "Mutual Bullfight",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/versus-niu-niu.jpg"),
    title: "Versus Niu-Niu",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/winning-thirteen.jpg"),
    title: "Winning Thirteen",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/fraud-jinhua.jpg"),
    title: "Fraud Jinhua",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/texas-holdem.jpg"),
    title: "Texas Hold'em",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/fight-the-landlord.jpg"),
    title: "Fight the Landlord",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/black-jack.jpg"),
    title: "Black Jack",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/show-hand.jpg"),
    title: "Show Hand",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/pai-gow.jpg"),
    title: "Pai Gow",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/3-card-poker.jpg"),
    title: "3-card poker",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/spred-bullfight.jpg"),
    title: "Spread Bullfight",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/rich-baccarat.jpg"),
    title: "Rich Baccarat",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/versus-2-8-bar.jpg"),
    title: "versus 2-8 bar",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/versus-mahjong.jpg"),
    title: "Versus Mahjong",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/rivers-of-blood.jpg"),
    title: "Rivers of Blood",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/royal-bull-fight.jpg"),
    title: "Royal Bull-fight",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/tien-len.jpg"),
    title: "TIEN LEN",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/dummy.jpg"),
    title: "Dummy",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/3-3-3.jpg"),
    title: "เก้าเก",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/a-k-9.jpg"),
    title: "ไพ่ป๊อกเด้ง",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/card-ken.jpg"),
    title: "Card Ken",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/kings-queen.jpg"),
    title: "King's Queen",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/hundred-niu-niu.jpg"),
    title: "Hundred Niu-Niu",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/baccarat.jpg"),
    title: "Baccarat",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/drift-car-racing.jpg"),
    title: "Drift Car Racing",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/the-chinese-boxer.jpg"),
    title: "The Chinese Boxer",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/journey-to-the-west.jpg"),
    title: "Journey to the West",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/horse-racing.jpg"),
    title: "Horse Racing",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/2-8-bar.jpg"),
    title: "2-8 Bar",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/sic-bo.jpg"),
    title: "Sic bo",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/crab-and-shrimp.jpg"),
    title: "Crab and Shrimp",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/minesweeping.jpg"),
    title: "Minesweeping",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/animal-running.jpg"),
    title: "Animal Running",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/vietnamese-fish-prawn-crab.jpg"),
    title: "Vietnamese Fish-Prawn-Crab",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/car-parking.jpg"),
    title: "GA Car Parking",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/3d-game/list-3d-game/mini-ted/fan-tan.jpg"),
    title: "FAN TAN",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
];
