export const dataTopTrend = [
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/the-crown.jpg"),
    title: "The Crown",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/jelly-mania.jpg"),
    title: "Jelly Maina",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/viking-honour.jpg"),
    title: "Viking Honour",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/aloha-spirit-xtra-lock.jpg"),
    title: "Aloha Spirit Xtra Lock",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/lone-rider.jpg"),
    title: "Lone Rider",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/forgs-n-flies-h5.jpg"),
    title: "Frogs N Flies H5",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/silver-lion-h5.jpg"),
    title: "Silver Lion H5",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/rock-n-ways-xtraways.jpg"),
    title: "Rock N Ways XtraWays",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/thundering-zeus-h5.jpg"),
    title: "ThunderingZeus H5",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/book-of-the-east.jpg"),
    title: "Book of the East",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/samurai-blade.jpg"),
    title: "Samurai Blade",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/chilli-gold-h5.jpg"),
    title: "Chilli Gold H5",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/zombies-on-vacation.jpg"),
    title: "Zombies on Vacation",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/royal-rumble.jpg"),
    title: "Royal Rumble",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/mad-monkey-h5.jpg"),
    title: "Mad Monkey H5",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/santa-vs-aliens.jpg"),
    title: "Santa Vs Aliens",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/hachis-quest-of-heroes.jpg"),
    title: "HachisQuestOfHeroes",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/mega-phoenix.jpg"),
    title: "Mega Phoenix",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/dolphin-gold-h5.jpg"),
    title: "Dolphin Gold H5",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/pirate-treasure.jpg"),
    title: "Pirate Treasure",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/nc-baccarat.jpg"),
    title: "NCBaccarat",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/vikings-of-valhalla.jpg"),
    title: "Vikings of Valhalla",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/stoem-of-egypt.jpg"),
    title: "Storm of Egypt",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/five-princesses.jpg"),
    title: "Five Princesses",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/sea-god.jpg"),
    title: "Sea God",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/toptrendgaming/jorge-from-bergen.jpg"),
    title: "Jorge From Bergen",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
];
