export const dataHcSlot =[
    {
        image: require("../../assets/images/img-slot/list-slots/hcslot/fruits-777.jpg"),
        title: "Fruits 777",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: require("../../assets/images/img-slot/list-slots/hcslot/god-of-wealth-3.jpg"),
        title: "God of Wealth 3",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: require("../../assets/images/img-slot/list-slots/hcslot/ghost-bride.jpg"),
        title: "Ghost Bride",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: require("../../assets/images/img-slot/list-slots/hcslot/new-years-eve-3.jpg"),
        title: "New Year's Eve3",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/eqyptian-treasure.jpg"),
        title: "Egyptian Treasure",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/penalty-shootout-3.jpg"),
        title: "Penalty Shootout3",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/zodiac-3.jpg"),
        title: "Zodiac3",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/water-margin.jpg"),
        title: "Water Margin",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/card-slots.jpg"),
        title: "Card Slots",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/super-777.jpg"),
        title: "Super 777",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/the-journey-to-the-west.jpg"),
        title: "The Journey to the West",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/kungfu-panda.jpg"),
        title: "Kung Fu Panda",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/fortune.jpg"),
        title: "Fortune",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/dragons-war-megabonus.jpg"),
        title: "Dragons War MegaBonus",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/four-divine-beasts.jpg"),
        title: "Four Divine Beasts",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/blessings-coming-3.jpg"),
        title: "Blessings Coming3",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/zeus.jpg"),
        title: "Zeus",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/seek-extras.jpg"),
        title: "Seek Extras",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/sweetheart-night-megbonus.jpg"),
        title: "Sweetheart Night MegaBonus",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/mahjong-warrior.jpg"),
        title: "Mahjong Warrior",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/blessings-coming-megabonus.jpg"),
        title: "Blessings Coming MegaBonus",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/western-cowboy.jpg"),
        title: "Western Cowboy",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/diamond-coming.jpg"),
        title: "Diamond Coming",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/dragons-war.jpg"),
        title: "Dragons War",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/chinese-chess.jpg"),
        title: "Chinese chess",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/sweetheart-night.jpg"),
        title: "Sweetheart Night",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/snow-queen.jpg"),
        title: "Snow Queen",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/merry-christmas.jpg"),
        title: "Merry Christmas",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/counselor.jpg"),
        title: "Counselor",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/wu-song-biography-II.jpg"),
        title: "Wu Song Biography II",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/ganesa.jpg"),
        title: "Ganesa",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/chinese-chess-megabonus.jpg"),
        title: "Chinese chess MegaBonus",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/aladdin.jpg"),
        title: "Aladdin",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/king-of-club.jpg"),
        title: "King of Club",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/magic-carnival.jpg"),
        title: "Magic Carnival",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/sea-of-thieves.jpg"),
        title: "Sea of Thieves",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/angry-birds.jpg"),
        title: "Angry Birds",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/fire-queen.jpg"),
        title: "FIRE QUEEN",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/valhalla.jpg"),
        title: "Valhalla",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/wealth-jungle.jpg"),
        title: "Wealth Jungle",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/sherlock.jpg"),
        title: "Sherlock",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/puss-swords-man.jpg"),
        title: "Puss Swords Man",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/animal-forest-party.jpg"),
        title: "Animal Forest Party",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },{
        image: require("../../assets/images/img-slot/list-slots/hcslot/fishing-match.jpg"),
        title: "Fishing Match",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
]