export const dataGamePlay = [
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/wuxia-princess-mega-reels.jpg"),
    title: "Wuxia Princess Mega Reels",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/bai-ye-xing-fu.jpg"),
    title: "Bai Ye Xing Fu",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/god-of-fortune.jpg"),
    title: "God Of Fortune",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/fortune-dragon.jpg"),
    title: "Fortune Dragon",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/angry-bees.jpg"),
    title: "Angry Bees",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/alpha-and-the-red-hood.jpg"),
    title: "Alpha and the Red Hood",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/mine-of-riches.jpg"),
    title: "Mine of Riches",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/steampunk-bandits.jpg"),
    title: "Steampunk Bandits",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/chilli-surprise.jpg"),
    title: "Chilli Surprise",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/songkran-summer-splash.jpg"),
    title: "Songkran: Summer Splash",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/lion-dance.jpg"),
    title: "Lion Dance",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/double-greatness.png"),
    title: "Double Greatness",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/ufo-frenzy.jpg"),
    title: "UFO Frenzy",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/blossom-garden.jpg"),
    title: "Blossom Garden",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/lunar-legends.jpg"),
    title: "Lunar Legends",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/panda-warrior.jpg"),
    title: "Panda Warrior",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/elf-surprise-jackpot.jpg"),
    title: "Elf Surprise Jackpot",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/cash-and-kisses.jpg"),
    title: "Cash and Kisses",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/dino-age.jpg"),
    title: "Dino Age",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/genies-luck.jpg"),
    title: "Genies Luck",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/tigers-roar.jpg"),
    title: "Tiger's Roar",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/skater-king.jpg"),
    title: "Skater King",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/sweet-baker.jpg"),
    title: "Sweet Baker",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image:  require("../../assets/images/img-slot/list-slots/gameplay/sacred-clash.jpg"),
    title: "Sacred Clash",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image:  require("../../assets/images/img-slot/list-slots/gameplay/fa-fa-roulette.jpg"),
    title: "Fa Fa Roulette",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/gameplay/mystical-bali.jpg"),
    title: "Mystical Bali",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
];
