import {NEXTSPIN} from '../imagesSlots'

export const dataNextSpin = [
    {
        image: NEXTSPIN.Roma,
        title: "Roma",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.CandyBonanzaXmas,
        title: "Candy Bonanza Xmas",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.CandyBonanza,
        title: "Candy Bonaza",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.GoldenFa,
        title: "Golden Fa",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.FiveFortuneStarts,
        title: "Five Fortune Starts",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.LongLongLong,
        title: "Long Long Long",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.SevenDragons,
        title: "7 Dragons",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.BuffaloKing,
        title: "Buffalo King",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.GoldenWest,
        title: "Golden West",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.ClassicFruits,
        title: "Classic Fruits 7",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.ShakeThaiThai,
        title: "Shake Thai Thai",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.HotSmash,
        title: "Hot Smash",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.EternalFire,
        title: "Eternal Fire",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.FortuneToad,
        title: "Fortune Toad",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.SweetLava,
        title: "Sweet Lava",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.DragonBlitz,
        title: "Dragon Blitz",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.Diamon7,
        title: "Diamon 7",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.LightningWoman,
        title: "Lightning Woman",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.LuckyGame,
        title: "Lucky Game",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.OceanChest,
        title: "Ocean Chest",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.ShakeBoomBoom,
        title: "Shake Boom Boom",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.Taiga88,
        title: "Taiga 88",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.HolyGoat,
        title: "Holy Goat",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.CrazyMonkeyDeluxe,
        title: "Crazy Monkey Deluxe",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.DonkiKong,
        title: "Donki Kong",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.TripleMonkey,
        title: "Triple Monkey",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.HightWayBee,
        title: "Hightway Bee",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.SuperFortune,
        title: "Super Fortune",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.JokerKing,
        title: "Joker King",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.DoubleMonkey,
        title: "Double Monkey",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.DolphinDive,
        title: "Dolphin Dive",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.SoccerKing,
        title: "Soccer King",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.FruitTycoon,
        title: "Fruit Tycoon",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.RickyTycoon,
        title: "Ricky Tycoon",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.ForestSecret,
        title: "Forest Secret",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.PrincessOfCrime,
        title: "Princess of Crime",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.TwinkleIce,
        title: "Twinkle Ice",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.TripleKungfuMonkey,
        title: "Triple Kungfu Monkey",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.MrHippo,
        title: "Mr. Hippo",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.MayaQuest,
        title: "Maya Quest",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.Honey888,
        title: "Honey 888",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: NEXTSPIN.CrazyMonkey,
        title: "Crazy Monkey",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
]