import { PLAYTECH } from "../imagesSlots";

export const dataPlayTech = [
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: PLAYTECH,
    title: "",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
},
];
