import {MICROGAMING} from '../imagesSlots'

export const dataMicrogaming = [
    {
        image: MICROGAMING.LuckyTwinsWilds,
        title: "Lucky Twins Wilds",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.SoccerStriker,
        title: "Soccer Striker",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.PoseidonAncientFortuneMegaWays,
        title: "Ancient Fortunes : Poseidon Megaways™",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.SquealinRichesLockWin,
        title: "Squealin' Riches",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.LuckyTwins,
        title: "Lucky Twins",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.Wishes10000,
        title: "10000 Wishes",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AfricaXup,
        title: "Africa X UP",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.ZeusAncientFortunes,
        title: "Ancient Fortunes: Zeus",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BlazingMammothEpicStrike,
        title: "Blazing Mammoth",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AmazingLinkApollo,
        title: "Amazing Link™ Apollo",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.CatClans,
        title: "Cat Clans",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AmazingLinkZeus,
        title: "Amazing Link Zeus",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.HyperStart,
        title: "Hyper Start",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.LuckyClucks,
        title: "Lucky Clucks",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BreakAwayDeluxe,
        title: "Break Away Deluxe",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.MasksOfFire9,
        title: "9 Masks Of Fire",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.DragonsBreath,
        title: "Dragons Breath",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BreakDaBankAgainMegaways,
        title: "Break Da Bank Again™ MEGAWAYS™",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.TreasuresOfLionCity,
        title: "Treasures of Lion City",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.ChroniclesOfOlympusXup,
        title: "Chronicles of Olympus X Up",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.HyperGold,
        title: "Hyper Gold",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.FireForge,
        title: "Fire Forge",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.MasksOfFireHyperSpins9,
        title: "9 Masks of Fire™ HyperSpins™",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.FruitBlast,
        title: "Fruit Blast",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BookOfOzLocknSpin,
        title: "Book of Oz Lock 'N Spin",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.MegaDeluxe777,
        title: "777 Mega Deluxe™",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.EaglesWings,
        title: "Eagles's Wings",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.HyperStrikeHyperSpins,
        title: "Hyper Strike™ HyperSpins™",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BreakAwayShootout,
        title: "Break Away Shootout",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BustTheMansion,
        title: "Bust The Mansion",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.StarKnockout5,
        title: "5 Star Knockout",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.JurassicParkGold,
        title: "Jurassic Park Gold",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BigBoomRiches,
        title: "Big Boom Riches",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.KodiakKingdom,
        title: "Kodiak Kingdom",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.ArcticEnchantress,
        title: "Arctic Enchantress™",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BasketballStarWilds,
        title: "Basketball Star Wilds",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.DokiDokiParfait,
        title: "Doki Doki Parfait",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AgentJaneBloneMaxVolume,
        title: "Agent Jane Blone Max Volume",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BookOfMrsClaus,
        title: "Book of Mrs Claus",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.DiamondBlues4,
        title: "4 Diamond Blues Megaways™",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.FortuneRush,
        title: "Fortune Rush",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.WLegends,
        title: "WWE Legends",
        feature: "new",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AlchemyBlast,
        title: "Alchemy Blast",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AstroLegendsLyraandErion,
        title: "AstroLegends: Lyra and Erion",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BattleRoyale,
        title: "Battle Royale",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.CricketStarScratch,
        title: "Cricket Star Scratch",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.GalaxyGliderArcade,
        title: "Galaxy Glider",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.GemsOdyssey,
        title: "Gems Odyssey",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.HippieDays,
        title: "Hippie Days",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.InCanAdventureArcade,
        title: "InCan Adventure",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.JewelQuestRiches,
        title: "Jewel Quest Riches",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.LuckyTwinsCatcher,
        title: "Lucky Twins Catcher",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.MaxDamageArcade,
        title: "Max Damage and the Alien Attack",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.MonsterBlast,
        title: "Monster Blast",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.PetsGoWild,
        title: "Pets Go Wild",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.PokeTheGuy,
        title: "Poke The Guy",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.TheIncredibleBallonMachine,
        title: "Incredible Ballon Machine",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.TreasureDash,
        title: "Treasure Dash",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.Heroes108,
        title: "108 Heroes",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.HeroesMultiplierFortunes108,
        title: "108 Heroes Multiplier Fortunes",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.ReelDrive5,
        title: "5 Reel Drive",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.RoyalWheel777,
        title: "777 Royal Wheel",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.GoldenSkullofHollyRoger8,
        title: "8 Golden Skulls of Holly Roger Megaways ™",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BlazingDiamonds9,
        title: "9 Blazing Diamonds",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.PotsOfGold9,
        title: "9 Pots of Gold",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.ADarkMatter,
        title: "A Dark Matter",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AdventurePalace,
        title: "Adventure Palace",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AdventureOfDoubloonIsland,
        title: "Adventure Of Doubloon Island",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AgentJaneBlone,
        title: "Agent Jane Blone",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AgeOfConquets,
        title: "Age of Conquets",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AgeOfDiscovery,
        title: "Age of Discovery",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AlaskaFishing,
        title: "Alaskan Fishing",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AlchemistStone,
        title: "Alchemist Stone",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AlchemyFortunes,
        title: "Alchemy Fortunes",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.ArianaOnlineSlot,
        title: "Ariana",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AsianBeauty,
        title: "Asian Beauty",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AssassinMoon,
        title: "Assassin Moon",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.ATaleOfElves,
        title: "A Tale of Elves",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AtlantisRising,
        title: "Atlantis Rising",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.Augustus,
        title: "Augustus",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.AuroraWilds,
        title: "Aurora Wilds",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.Avalon,
        title: "Avalon",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BadmintonHero,
        title: "Badminton Hero",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BananaOdyssey,
        title: "Banana Odyssey",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BasketballStarOnlineSlot,
        title: "Basketball Star",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BasketballStarDeluxe,
        title: "Basketball Star Deluxe",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BasketballStarOnFire,
        title: "Basketball Star On Fire",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING.BigTop,
        title: "Big Top",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: MICROGAMING,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
]