export const dataPgSoft = [
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/treasures-aof-aztec.jpg"),
    title: "Treasures of Aztec",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/lucky-neko.jpg"),
    title: "Lucky Neko",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/mahjong-ways-2.jpg"),
    title: "Mahjong Ways 2",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/caishen-wins.jpg"),
    title: "Caishen Wins",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/fortune-ox.jpg"),
    title: "Fortune Ox",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/mahjong-ways.jpg"),
    title: "Mahjong Ways",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/ways-of-the-qilin.jpg"),
    title: "Ways of the Qilin",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/ganesha-fortune.jpg"),
    title: "Ganesha Fortune",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/fotrune-tiger.jpg"),
    title: "Fortune Tiger",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/cocktail-nights.jpg"),
    title: "Cocktail Nights",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/wild-bandito.jpg"),
    title: "Wild Bandito",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/the-queens-banquet.jpg"),
    title: "The Queen's Banquet",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/jurassic-kingdom.jpg"),
    title: "Jurassic Kingdom",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/thai-river-wonders.jpg"),
    title: "Thai River Wonders",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/fortune-mouse.jpg"),
    title: "Fortune Mouse",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/rooster-rumble.jpg"),
    title: "Rooster Rumble",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/egypts-book-of-mystery.jpg"),
    title: "Egypt's Book of Mystery",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/butterfly-blossom.jpg"),
    title: "Butterfly Blossom",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/dragon-hatch.jpg"),
    title: "Dragon Hatch",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/queen-of-bounty.jpg"),
    title: "Queen of Bounty",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/oriental-prosperity.jpg"),
    title: "Oriental Prosperity",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
   },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/dream-of-macau.jpg"),
    title: "Dreams of Macau",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/destiny-of-sun-moon.jpg"),
    title: "Destiny of Sun & Moon",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/captains-bounty.jpg"),
    title: "Captain's Bounty",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/double-fortune.jpg"),
    title: "Double Fortune",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/leprechaun-riches.jpg"),
    title: "Leprechaun Riches",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/garuda-gems.jpg"),
    title: "Garuda Gems",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/spirited-wonders.jpg"),
    title: "Spirited Wonders",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/secret-og-cleopatra.jpg"),
    title: "Secret of Cleopatra",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/majestic-treasures.jpg"),
    title: "Majestic Treasures",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/supermarket-spree.jpg"),
    title: "Supermarket Spree",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/battleground-royale.jpg"),
    title: "Battleground Royale",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/mask-carnival.jpg"),
    title: "Mask Carnival",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/farm-invaders.jpg"),
    title: "Farm Invaders",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/emoji-riches.jpg"),
    title: "Emoji Riches",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/legendary-monkey-king.jpg"),
    title: "Legendary Monkey King",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/raider-janes-crypt-of-fortune.jpg"),
    title: "Raider Jane's Crypt of Fortune",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/buffalo-win.jpg"),
    title: "Buffalo Win",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/groundhog-harvest.jpg"),
    title: "Groundhog Harvest",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/mermaid-riches.jpg"),
    title: "Mermaid Riches",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/sushi-oishi.jpg"),
    title: "Sushi Oishi",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/opera-dynasty.jpg"),
    title: "Opera Dynasty",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/bali-vacation.jpg"),
    title: "Bali Vacation",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/crypto-gold.jpg"),
    title: "Crypto Gold",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/candy-bonanza.jpg"),
    title: "Candy Bonanza",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/heist-stakes.jpg"),
    title: "Heist Stakes",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/rise-of-apollo.jpg"),
    title: "Rise of Apollo",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/baccarat-deluxe.jpg"),
    title: "Baccarat Deluxe",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/bikini-paradise.jpg"),
    title: "Bikini Paradise",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/candy-burst.jpg"),
    title: "Candy Burst",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/circus-delight.jpg"),
    title: "Circus Delight",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/dim-sum-mania.jpg"),
    title: "Dim Sum Mania",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/dragon-tiger-luck.jpg"),
    title: "Dragon Tiger Luck",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/emperors-favour.jpg"),
    title: "Emperor's Favour",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/flirting-scholar.jpg"),
    title: "Flirting Scholar",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/ganesha-gold.jpg"),
    title: "Ganesha Gold",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/gem-saviour.jpg"),
    title: "Gem Saviour",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/gem-saviour-conquest.jpg"),
    title: "Gem Saviour Conquest",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/gem-saviour-sword.jpg"),
    title: "Gem Saviour Sword",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/genies-3-wishes.jpg"),
    title: "Genie's 3 Wishes",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/hip-hop-panda.jpg"),
    title: "Hip Hop Panda",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/honey-trap-of-diao-chan.jpg"),
    title: "Honey Trap of Diao Chan",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/hood-vs-wolf.jpg"),
    title: "Hood vs Wolf",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/hot-pot.jpg"),
    title: "Hotpot",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/jewels-of-prosperity.jpg"),
    title: "Jewels of Prosperity",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/journey-to-the-wealth.jpg"),
    title: "Journey to the Wealth",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/jungle-delight.jpg"),
    title: "Jungle Delight",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/legend-of-hou-yi.jpg"),
    title: "Legend of Hou Yi",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/medusa.jpg"),
    title: "Medusa",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/medusa-II.jpg"),
    title: "Medusa II",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/mr-hallow-win.jpg"),
    title: "Mr. Hallow-Win",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/muay-thai-champion.jpg"),
    title: "Muay Thai Champion",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/ninja-vs-samurai.jpg"),
    title: "Ninja vs Samurai",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/phoenix-rises.jpg"),
    title: "Phoenix Rises",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/piggy-gold.jpg"),
    title: "Piggy Gold",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/plushie-frenzy.jpg"),
    title: "Plushie Frenzy",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/reel-love.jpg"),
    title: "Reel Love",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/wizdom-wonders.jpg"),
    title: "Wizdom Wonders",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/win-win-won.jpg"),
    title: "Win Win Won",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/wild-fireworks.jpg"),
    title: "Wild Fireworks",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/vampires-charm.jpg"),
    title: "Vampire's Charm",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/tree-of-fortune.jpg"),
    title: "Tree of Fortune",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/three-monkeys.jpg"),
    title: "Three Monkeys",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/the-great-icescape.jpg"),
    title: "The Great Icescape",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/symbols-of-egypt.jpg"),
    title: "Symbols of Egypt",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/santas-gift-rush.jpg"),
    title: "Santa's Gift Rush",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/shaolin-soccer.jpg"),
    title: "Shaolin Soccer",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/galactic-gems.jpg"),
    title: "Galactic Gems",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/jack-frosts-winter.jpg"),
    title: "Jack Frost's Winter",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pgsoft/guardians-of-ice-and-fire.jpg"),
    title: "Guardians of Ice and Fire",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
];
