export const dataAsiaGaming = [
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/gold-class.jpg"),
    title: "Gold Class",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/the-dragon-pearl-gold.jpg"),
    title: "The Dragon Pearl Gold",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/mahjong-slot.jpg"),
    title: "Mahjong slots",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/space-odyssey.jpg"),
    title: "Space Odyssey",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/pillar-of-fortune.jpg"),
    title: "Pillar of Fortune",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/lucky-riches.jpg"),
    title: "Lucky Riches",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/fruit-slot.jpg"),
    title: "Fruit slots",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/vegas-vegas.jpg"),
    title: "Vegas Vegas",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/wild-777.jpg"),
    title: "Wild 777",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/royal-gems.jpg"),
    title: "Royal Gems",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/god-of-wu-fortune.jpg"),
    title: "God of Wu Fortune",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/garden-vintage.jpg"),
    title: "Garden Vintage",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/sex-and-zen.jpg"),
    title: "Sex and Zen",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/gold-class-deluxe.jpg"),
    title: "Gold Class Deluxe",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/legend-of-the-dragon.jpg"),
    title: "Legend of the Dragon",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/evil-dragon.jpg"),
    title: "Evil Dragons",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/pirates-ahoy.jpg"),
    title: "Pirates Ahoy!",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/wild-gods.jpg"),
    title: "Wild Gods",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/kong-invasion.jpg"),
    title: "Kong Invasion",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/samurai-slot.jpg"),
    title: "Samurai slots",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/sexy-succubus-en.jpg"),
    title: "Sexy Succubus",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/kung-fu-all-stars.jpg"),
    title: "Kung Fu All Stars",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/year-of-the-monkey.jpg"),
    title: "Year of the Monkey",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/mr-xin.jpg"),
    title: "Mr XIN",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/candy-quest.jpg"),
    title: "Candy Quest",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/asiagaming/knight-and-dragon.jpg"),
    title: "Knight and Dragon",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
];
