import { JILI } from "../imagesSlots";

export const dataJili = [
  {
    image: JILI.RomaX,
    title: "RomaX",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.SuperAce,
    title: "Super Ace",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.FortuneGems,
    title: "Fortune Gems",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.GoloenEmpire,
    title: "Goloen Empire",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.Alibaba,
    title: "Ali Baba",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.MoneyComing,
    title: "Money Coming",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.CrazyHunter,
    title: "Crazy Hunter",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.Sevenx3Fire,
    title: "Crazy Seven",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.MegaAce,
    title: "Mega Ace",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.BoxingKing,
    title: "Boxing King",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.PharaohTreasure,
    title: "Pharaoh Treasure",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.ChinShiHuang,
    title: "Chin Shi Huang",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.ChargeBuffalo,
    title: "Charge Buffalo",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.JungleKing,
    title: "Jungle King",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.BubbleBeauty,
    title: "Bubble Beauty",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.SecretTreasure,
    title: "Secret Treasure",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.GoldenBank,
    title: "Crazy Golden Bank",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.FengShen,
    title: "Feng Shen",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.Medusa,
    title: "Medusa",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.PartyNight,
    title: "Party Night",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.DragonTreasure,
    title: "Dragon Treasure",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.ShangHaiBeauty,
    title: "Shanghai Beauty",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.MagicLamp,
    title: "Magic Lamp",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.WarOfDragon,
    title: "War of Dragon",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.SuperRich,
    title: "Super Rich",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.BaoBoonChin,
    title: "Bao Boon Chin",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.LuckyComing,
    title: "Lucky Coming",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.GoldenQueen,
    title: "Golden Queen",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.Sevenx3Thunder,
    title: "SevenSevenSeven",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.FortunePig,
    title: "Fortune Pig",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.FaFaFa,
    title: "Fa Fa Fa",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.LuckyLady,
    title: "Lucky Lady",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.TwinWins,
    title: "Twin Wins",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.AngentAce,
    title: "Angent Ace",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.GemParty,
    title: "Gem Party",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.HotChilli,
    title: "Hot Chilli",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.FortuneTree,
    title: "Fortune Tree",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.LuckyBoll,
    title: "Lucky Ball",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.HyperBurst,
    title: "Hyper Burst",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.GodOfMartial,
    title: "God of Martial",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.CrazyFafafa,
    title: "Crazy Fafafa",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.XiyangYang,
    title: "Xiyang Yang",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.CandyBaby,
    title: "Candy Baby",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.LuckyGoldBricks,
    title: "Lucky Gold Bricks",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.MonkeyParty,
    title: "Monkey Party",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.DragonTiger,
    title: "Dragon & Tiger",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.Dice,
    title: "Dice",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.SevenUpDown,
    title: "7 Up Down",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: JILI.LuckyNumber,
    title: "Lucky Number",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
];
