export const dataNetEnt = [
  {
    image: require("../../assets/images/img-slot/list-slots/netent/starburs.jpg"),
    title: "Starburst",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/baccarat.jpg"),
    title: "Baccarat",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/blackjack.jpg"),
    title: "Blackjack",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/fruit-shop.jpg"),
    title: "Fruit Shop",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/reel-rush.jpg"),
    title: "Reel Rush",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/blood-suckers.jpg"),
    title: "Blood Suckers",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/twin-spin.jpg"),
    title: "Twin Spin",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/gonzos-quest.jpg"),
    title: "Gonzo's Quest",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/dazzle-me.jpg"),
    title: "Dazzle Me",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/steam-tower.jpg"),
    title: "Steam Tower",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/jack-hammer.jpg"),
    title: "Jack Hammer",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/pyramid-quest-for-immortality.jpg"),
    title: "Pyramid: Quest for Immortality",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/dead-or-alive-2-feature-buy.jpg"),
    title: "Dead or Alive 2 Feature Buy",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/fruit-shop-megaways.jpg"),
    title: "Fruit Shop Megaways",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/wild-wild-west-the-great-train-heist.jpg"),
    title: "Wild Wild West: The Great Train Heist",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/finn-and-the-swirly-spin.jpg"),
    title: "Finn and the Swirly Spin",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/twin-spin-megaways.jpg"),
    title: "Twin Spin Megaways",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/jack-and-the-beanstalk.jpg"),
    title: "Jack and the Beanstalk",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/aloho-cluster-pays.jpg"),
    title: "Aloha! Cluster Pays",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/divine-fortune-megaways.jpg"),
    title: "Divine Fortune Megaways",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/jack-hammer-2-fishy-business.jpg"),
    title: "Jack Hammer 2: Fishy Business",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/koi-princess.jpg"),
    title: "Koi Princess",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/space-wars.jpg"),
    title: "Space Wars",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/asgardian-stones.jpg"),
    title: "Asgardian Stones",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/hot-line.jpg"),
    title: "Hotline",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/netent/blood-suckers-ii.jpg"),
    title: "Blood Suckers II",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
];
