export const dataPragmaticPlay = [
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/gates-of-olympus.jpg"),
    title: "Gates of Olympus",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/bk8-sweet-blaster.jpg"),
    title: "BK8 Sweet Blaster",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/starlight-pricess.jpg"),
    title: "Starlight Princess",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/sweet-bonanza-xmas.jpg"),
    title: "Sweet Bonanza Xmas",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/aztec gems.jpg"),
    title: "Aztec Gems",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/pyramid-bonanza.jpg"),
    title: "Pyramid Bonanza",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/bonanza-gold.jpg"),
    title: "Bonanza Gold",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/5-lion-megaways.jpg"),
    title: "5 Lions Megaways",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/jokers-jewels.jpg"),
    title: "Joker's Jewels",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/great-rhino-megaways.jpg"),
    title: "Great Rhino Megaways",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/candy-village.jpg"),
    title: "Candy Village",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/wild-west-gold.jpg"),
    title: "Wild West Gold",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/fire-strike.jpg"),
    title: "Fire Strike",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/aztec-gems-deluxe.jpg"),
    title: "Aztec Gems Deluxe",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/aztec-bonanza.jpg"),
    title: "Aztec Bonanza",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/power-of-thor-megaways.jpg"),
    title: "Power of Thor Megaways™",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/christmas-carol-megaways.jpg"),
    title: "Christmas Carol Megaways",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/madame-destiny-megaways.jpg"),
    title: "Madame Destiny Megaways™",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/john-hunter-and-the-tomb-of-the-scarab-queen.jpg"),
    title: "John Hunter and the Tomb of the Scarab Queen",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/buffalo-king-megaways.jpg"),
    title: "Buffalo King Megaways",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/the-dog-house.jpg"),
    title: "The Dog House",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/extra-juicy-megaways.jpg"),
    title: "Extra Juicy Megaways",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/gems-bonanza.jpg"),
    title: "Gems Bonanza",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/the-amazing-money-machine.jpg"),
    title: "The Amazing Money Machine",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/rise-of-samurai-megaways.jpg"),
    title: "Rise of Samurai Megaways",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/pragmaticplay/the-dog-house-megaways.jpg"),
    title: "The Dog House Megaways™",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
];
