export const dataPlaynGo = [
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/rise-of-olympus.jpg"),
    title: "Rise of Olympus",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/moon-princess.jpg"),
    title: "Moon Princess",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/tome-of-madness.jpg"),
    title: "Tome of Madness",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/golden-ticket.jpg"),
    title: "Golden Ticket",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/moon-princess-100.jpg"),
    title: "Moon Princess 100",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/gemix.jpg"),
    title: "GEMiX",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/sweet-alchemy.jpg"),
    title: "Sweet Alchemy",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/reactoonz.jpg"),
    title: "Reactoonz",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/xmas-joker.jpg"),
    title: "Xmas Joker",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/big-win-cat.jpg"),
    title: "Big Win Cat",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/golden-ticket-2.jpg"),
    title: "Golden Ticket 2",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/sea-hunter.jpg"),
    title: "Sea Hunter",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/mystery-joker.jpg"),
    title: "Mystery Joker",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/book-of-dead.jpg"),
    title: "Book of Dead",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/energoonz.jpg"),
    title: "Energoonz",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/gigantoonz.jpg"),
    title: "Gigantoonz",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/black-manba.jpg"),
    title: "Black Mamba",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/reactoonz.png"),
    title: "Reactoonz 2",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/honey-rush.jpg"),
    title: "Honey Rush",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/wild-frames.jpg"),
    title: "Wild Frames",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/fire-joker.jpg"),
    title: "Fire Joker",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/rainforest-magic.jpg"),
    title: "Rainforest Magic",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/legacy-of-dead.jpg"),
    title: "Legacy of Dead",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/raging-rex-2.jpg"),
    title: "Raging Rex 2",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/prosperity-palace.jpg"),
    title: "Prosperity Palace",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/gold-king.jpg"),
    title: "Gold King",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/troll-hunters-2.jpg"),
    title: "Troll Hunters 2",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/free-reelins-jocker.jpg"),
    title: "Free Reelin' Joker",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/pimped.jpg"),
    title: "Pimped",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },{
    image: require("../../assets/images/img-slot/list-slots/playgo/troll-hunters.jpg"),
    title: "Troll Hunters",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/phoenix-reborn.jpg"),
    title: "Phoenix Reborn",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/rocco-gallo.jpg"),
    title: "Rocco Gallo",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/cat-wilde-and-the-pyramids-of-dead.jpg"),
    title: "Cat Wilde and the Pyramids of Dead",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/wild-trigger.jpg"),
    title: "Wild Trigger",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/animal-madness.jpg"),
    title: "Animal Madness",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/idol-of-fortune.jpg"),
    title: "Idol of Fortune",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/kings-mask.jpg"),
    title: "King's Mask",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/pueble-parade.jpg"),
    title: "Puebla Parade",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/forge-of-gems.jpg"),
    title: "Forge of Gems",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },{
    image: require("../../assets/images/img-slot/list-slots/playgo/eye-of-atum.jpg"),
    title: "Eye of Atum",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/safari-of-wealth.jpg"),
    title: "Safari of Wealth",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/tales-of-asgard-freyas-wedding.jpg"),
    title: "Tales of Asgard: Freya's Wedding",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/fat-frankies.jpg"),
    title: "Fat Frankies",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/cat-wilde-and-the-lost-chapter.jpg"),
    title: "Cat Wilde and the Lost Chapter",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/hotel-yeti-way.jpg"),
    title: "Hotel Yeti-Way",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/prims-of-gems.jpg"),
    title: "Prism of Gems",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/secret-of-dead.jpg"),
    title: "Secret of Dead",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/muerto-en-mictlan.jpg"),
    title: "Muerto en Mictlan",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/the-wild-class.jpg"),
    title: "The Wild Class",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },{
    image: require("../../assets/images/img-slot/list-slots/playgo/sparky-shortz.jpg"),
    title: "Sparky&Shortz",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/perfect-gems.jpg"),
    title: "Perfect Gems",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/rise-of-merlin.jpg"),
    title: "Rise of Merlin",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/mission-cash.jpg"),
    title: "Mission Cash",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/inferno-joker.jpg"),
    title: "Inferno Joker",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/3-hand-casino-holdem.jpg"),
    title: "3-Hand Casino",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/cash-pump.jpg"),
    title: "Cash Pump",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/demon.jpg"),
    title: "Demon",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/xmas-magic.jpg"),
    title: "Xmas Magic",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/hot-bingo.jpg"),
    title: "Hot Bingo",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },{
    image: require("../../assets/images/img-slot/list-slots/playgo/divine-showdown.jpg"),
    title: "Divine Showdown",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/doom-of-egypt.jpg"),
    title: "Doom of Egypt",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/ankh-of-anubis.jpg"),
    title: "Ankh of Anubis",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/chronos-joker.jpg"),
    title: "Chronos Joker",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/big-win-777.jpg"),
    title: "Big Win 777",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/wildhound-derby.jpg"),
    title: "Wildhound Derby",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/wild-blood-2.jpg"),
    title: "Wild Blood 2",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/leprechaun-goes-wild.jpg"),
    title: "Leprechaun Goes Wild",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/coywolf-cash.jpg"),
    title: "Coywolf Cash",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/dawn-of-egypt.jpg"),
    title: "Dawn of Egypt",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },{
    image: require("../../assets/images/img-slot/list-slots/playgo/fortunes-of-ali-baba.jpg"),
    title: "Fortunes of Ali Baba",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/testament.jpg"),
    title: "Testament",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/riches-of-robin.jpg"),
    title: "Riches of Robin",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/ring-of-odin.jpg"),
    title: "Ring of Odin",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/thats-rich.jpg"),
    title: "That's Rich",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/sticky-joker.jpg"),
    title: "Sticky Joker",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/agent-destiny.jpg"),
    title: "Agent Destiny",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/annihilator.jpg"),
    title: "Annihilator",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/charlie-chance-in-hell-to-pay.jpg"),
    title: "Charlie Chance in Hell to Pay",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/rainforest-magic-bingo.jpg"),
    title: "Rainforest Magic Bingo",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },{
    image: require("../../assets/images/img-slot/list-slots/playgo/sweet-alchemy-bingo.jpg"),
    title: "Sweet Alchemy Bingo",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/rally-4-riches.jpg"),
    title: "Rally 4 Riches",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/rich-wild-and-the-shield-of-athena.jpg"),
    title: "Rich Wilde and the Shield of Athena",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/wilde-and-the-doom-of-dead.jpg"),
    title: "Wilde and the Doom of Dead",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/gold-volcano.jpg"),
    title: "Gold Volcano",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/win-a-beest.jpg"),
    title: "Win-A-Beest",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/blinged.jpg"),
    title: "Blinged",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/riddle-reels-a-case-of-riches.jpg"),
    title: "Riddle Reels: A Case of Riches",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/jolly-roger-2.jpg"),
    title: "Jolly Roger 2",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/celebration-of-wealth.jpg"),
    title: "Celebration of Wealth",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },{
    image: require("../../assets/images/img-slot/list-slots/playgo/octopus-treasure.jpg"),
    title: "Octopus Treasure",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/diamond-vortex.jpg"),
    title: "Diamond Vortex",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/beast-of-wealth.jpg"),
    title: "Beast of Wealth",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/temple-of-wealth.jpg"),
    title: "Temple of Wealth",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/feline-fury.png"),
    title: "Feline Fury",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/rabbit-hole-riches.png"),
    title: "Rabbit Hole Riches",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/madame-lnk.png"),
    title: "Madame Ink",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/dissco-diamond.jpg"),
    title: "Disco Diamonds",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/holiday-spirits.jpg"),
    title: "Holiday Spirits",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/rise-of-athena.jpg"),
    title: "Rise of Athena",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },{
    image: require("../../assets/images/img-slot/list-slots/playgo/viking-runecraft-bingo.jpg"),
    title: "Viking Runecraft Bingo",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/24-k-dragon.jpg"),
    title: "24K Dragon",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/new-year-riches.jpg"),
    title: "New Year Riches",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/ice-joker.jpg"),
    title: "Ice Joker",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/frozen-gems.jpg"),
    title: "Frozen Gems",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/golden-osiris.jpg"),
    title: "Golden Osiris",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/piggy-bank-farm.jpg"),
    title: "Piggy Bank Farm",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/coils-of-cash.jpg"),
    title: "Coils of Cash",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/miner-donkey-trouble.jpg"),
    title: "Miner Donkey Trouble",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/bull-in-a-china-shop.jpg"),
    title: "Bull in a China Shop",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },{
    image: require("../../assets/images/img-slot/list-slots/playgo/lord-merlin-and-the-lady-of-the-lake.jpg"),
    title: "Lord Merlin and the Lady of the Lake",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/the-paying-piano-club.jpg"),
    title: "The Paying Piano Club",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/thunder-screech.jpg"),
    title: "Thunder Screech",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/cat-wilde-in-the-eclipsse-of-the-sun-god.jpg"),
    title: "Cat Wilde in the Eclipse of the Sun God",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/the-faces-of-freya.jpg"),
    title: "The Faces of Freya",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/the-green-knight.jpg"),
    title: "The Green Knight",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/house-of-doom-2-the-crypt.jpg"),
    title: "House of Doom 2: The Crypt",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/shimmering-woods.jpg"),
    title: "Shimmering Woods",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/fire-toad.jpg"),
    title: "Fire Toad",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/rich-wilde-and-the-amulet-of-dead.jpg"),
    title: "Rich Wilde and The Amulet of Dead",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },{
    image: require("../../assets/images/img-slot/list-slots/playgo/fire-joker-freeze.jpg"),
    title: "Fire Joker Freeze",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/court-of-hearts.jpg"),
    title: "Court of Hearts",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/3-clown-monty.jpg"),
    title: "3 Clown Monty",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/scroll-of-dead.jpg"),
    title: "Scroll of Dead",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/playgo/charlie-chance.jpg"),
    title: "Charlie Chance",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Candy Island Princess",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Gemix 2",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Blazin’ Bullfrog",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Pack and Cash",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Odin: Protector of Realms",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },{
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Diamonds of the Realm",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Agent of Hearts",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Ghost of Dead",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Dr. Toonz",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Sisters of The Sun",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Charlie Chance and The Curse of Cleopatra",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Tales of Asgard: Loki's Fortune",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Legend of the Ice Dragon",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "The Last Sundown",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Moon Princess: Christmas Kingdom",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },{
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Merlin and the Ice Queen Morgana",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Rich Wilde and the Wandering City",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Love Joker",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "15 Crystal Roses: A Tale of Love",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Tale of Kyubiko",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Hooligan Hustle",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Beasts of Fire",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Captain Xeno's Earth Adventur",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Rocco Gallo",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Idol of Fortune",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },{
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "King's Mask",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Cat Wilde and the Pyramids of Dead",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Animal Madness",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Wild Trigger",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Mini Baccarat",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Firefly Frenzy",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "The Sword and The Grail",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Wild Rails",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Rise of Dead",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Casino Stud Poker",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },{
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Single Deck BlackJack MH",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Dragon Ship",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Chinese New Year",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Aztec Idols",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Banana Rock",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Raging Rex",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "5x Magic",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "7 Sins",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Ace of Spades",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Bakers Treat",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },{
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Bell of Fortune",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "BlackJack MH",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Cats and Cash",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Cops n Robbers",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Crazy Cows",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Deuces Wild MH",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Double Exposure BlackJack MH",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Easter Eggs",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Enchanted Crystals",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Enchanted Meadow",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },{
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "European Roulette Pro",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Eye of the Kraken",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Fortune Teller",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Fruit Bonanz",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "FU ER DAI",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Gift Shop",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Gold Trophy 2",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Golden Caravan",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Golden Goal",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Golden Legend",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },{
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Grim Muerto",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Gunslinger: Reloaded",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Happy Halloween",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Holiday Season",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "House of Doom",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Imperial Opera",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Irish Gold",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Iron Girl",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Jackpot Poker",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Jacks or Better MH",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },{
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Jade Magician",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Jewel Box",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Joker Poker MH",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Jolly Roger",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Lady of Fortune",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Legacy of Egypt",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Leprechaun goes Egypt",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Leprechaun goes to Hell",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Lucky Diamonds",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Matsuri",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },{
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Mermaids Diamond",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Merry Xmas",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Money Wheel",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "MULTIFRUIT 81",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Mystery Joker 6000",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Myth",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Ninja Fruits",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Pearl Lagoon",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Pearls of India",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Photo Safari",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },{
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Planet Fortune",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Prissy Princess",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Rage to Riches",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Riches of RA",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Royal Masquerade",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Sails of Gold",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Samba Carnival",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Sizzling Spins",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Space Race",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Speed Cash",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },{
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Spin Party",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Street Magic",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Super Flip",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Super Wheel",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Sweet 27",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Tower Quest",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Viking Runecraft",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Wild Blood",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Wild Melon",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Wild North",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Wizard of Gems",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Golden Colts",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Contact",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Mahjong 88",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Sabaton",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
//   {
//     image: require("../../assets/images/img-slot/list-slots/playgo"),
//     title: "Keno",
//     feature: "",
//     linkPlay: "#",
//     linkDemo: "#",
//   },
];
