export const dataFunkyGame = [
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/virtual-baccarat.jpg"),
    title: "VirtualBaccarat",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/football-strike.jpg"),
    title: "FootballStrike",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/baccarat-babes.jpg"),
    title: "Baccarat Babes",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/fish-prawn-crab.jpg"),
    title: "FishPrawnCrab",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/lucky-wheel.jpg"),
    title: "LuckyWheel",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/fafafa-2.jpg"),
    title: "FaFaFa2",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/777-blazing.jpg"),
    title: "777 Blazing",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/fafafa.jpg"),
    title: "FaFaFa",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/pokdeng.jpg"),
    title: "PokDeng",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/cai-shens-fortune.jpg"),
    title: "CaiShensFortune",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/sparta.jpg"),
    title: "Sparta",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/golden-dynasty.jpg"),
    title: "GoldenDynasty",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/fortune-goddess.jpg"),
    title: "Fortune Goddess",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/caribbean-saga.jpg"),
    title: "CaribbeanSaga",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/thunder-feng-shen.jpg"),
    title: "ThunderFengShen",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/fan-tan.jpg"),
    title: "FanTan",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/5-dragons-legend.jpg"),
    title: "5 Dragons Legend",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/southern-queen.jpg"),
    title: "Southern Queen",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/poker-slam.jpg"),
    title: "Poker Slam",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/shui-hu-heroes.jpg"),
    title: "ShuiHuHeroes",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/white-lion.jpg"),
    title: "White Lion",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/ji-ji-ji.jpg"),
    title: "Ji Ji Ji",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/speed-lotto.jpg"),
    title: "Speed Lotto",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/eros.jpg"),
    title: "Eros",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/domino-gaple-bet.jpg"),
    title: "Domino GapleBet",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/the-dragon-and-chinese-quiling.jpg"),
    title: "The Dragon and Chinese Qiling",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/classic-fruit.jpg"),
    title: "Classic Fruit",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/treasure-of-caishen.jpg"),
    title: "Treasure Of Caishen",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/orc.jpg"),
    title: "ORC",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/the-circus-night.jpg"),
    title: "The Circus Night",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/digging-gold.jpg"),
    title: "Digging Gold",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/tattoos.jpg"),
    title: "Tattoos",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/dj-queen.jpg"),
    title: "DJ QUEEN",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/angel-devil-new.jpg"),
    title: "Angel & Devil",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/legend-of-chu-han.jpg"),
    title: "Legend of Chu&Han",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/funkygames/civilizaion.jpg"),
    title: "Civilization",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
];
