export const dataHabanero = [
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/hot-hot-fruit.jpg"),
    title: "Hot Hot Fruit",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/koi-gate.jpg"),
    title: "Koi Gate",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/wealth-inn.jpg"),
    title: "Wealth Inn",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/mystic-fortune-deluxe.jpg"),
    title: "Mystic Fortune Deluxe",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/wild-trucks.jpg"),
    title: "Wild Trucks",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/disco-beats.jpg"),
    title: "Disco Beats",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/5-lucky-lions.jpg"),
    title: "5 Lucky Lions",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/lantern-luck.jpg"),
    title: "Lantern Luck",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/lucky-durian.jpg"),
    title: "Lucky Durian",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/happiest-christmas-tree.jpg"),
    title: "Happiest Christmas Tree",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/fa-cai-shen-deluxe.jpg"),
    title: "Fa Cai Shen Deluxe",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/fa-cai-shen.jpg"),
    title: "Fa Cai Shen",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/hot-hot-halloween.jpg"),
    title: "Hot Hot Halloween",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/four-divine-beasts.jpg"),
    title: "Four Divine Beasts",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/new-years-bash.jpg"),
    title: "New Years Bash",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/nini-tails.jpg"),
    title: "Nine Tails",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/lucky-lucky.jpg"),
    title: "Lucky Lucky",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/wizards-want-war.jpg"),
    title: "Wizards Want War!",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/hey-sushi.jpg"),
    title: "Hey Sushi",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/scopa.jpg"),
    title: "Scopa",
    feature: "",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/prost.jpg"),
    title: "Prost!",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/fly.jpg"),
    title: "Fly!",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/calaveras-explosivas.jpg"),
    title: "Calaveras Explosivas",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/marvelous-furlongs.jpg"),
    title: "Marvelous Furlongs",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/candy-tower.jpg"),
    title: "Candy Tower",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/habanero/return-to-the-feature.jpg"),
    title: "Return To The Feature",
    feature: "new",
    linkPlay: "#",
    linkDemo: "#",
  },
];
