export const dataRedTiger = [
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/dragons-luck.jpg"),
    title: "Dragon's Luck",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/winter-wonders.jpg"),
    title: "Winter Wonders",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/pirates-plenty-megaways.jpg"),
    title: "Pirates' Plenty MegaWays",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/chinese-treasures.jpg"),
    title: "Chinese Treasures",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/golden-offer.jpg"),
    title: "Golden Offer",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/dragons-luck-poewr-reels.jpg"),
    title: "Dragon's Luck Power Reels",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/pirates-plenty-battle-for-gold.jpg"),
    title: "Pirates' Plenty Battle for Gold",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/dragons-luck-deluxe.jpg"),
    title: "Dragon's Luck Deluxe",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/mystery-reels.jpg"),
    title: "Mystery Reels",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/dragons-fire.jpg"),
    title: "Dragon's Fire",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/piggy-riches-megaways.jpg"),
    title: "Piggy Riches Megaways",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/fortune-house.jpg"),
    title: "Fortune House",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/cash-ultimate.jpg"),
    title: "Cash Ultimate",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/rainbow-jackpots.jpg"),
    title: "Rainbow Jackpots",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/magic-gate.jpg"),
    title: "Magic Gate",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/10001-nights.jpg"),
    title: "10,001 Nights",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/phoenix-fire-power-reels.jpg"),
    title: "Phoenix Fire Power Reels",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/777-strike.jpg"),
    title: "777 Strike",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/devils-number.jpg"),
    title: "Devil's Number",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/golden-lotus.jpg"),
    title: "Golden Lotus",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/epic-journey.jpg"),
    title: "Epic Journey",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/five-star.jpg"),
    title: "Five Star",
    feature: "new",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/grand-wheel.jpg"),
    title: "Grand Wheel",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/jingle-bells.jpg"),
    title: "Jingle Bells",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/pirates-plenty.jpg"),
    title: "Pirates' Plenty",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
  {
    image: require("../../assets/images/img-slot/list-slots/redtiger/dragons-fire-megaways.jpg"),
    title: "Dragon's Fire Megaways",
    feature: "",
    linkPlay: "#",
    linkDemo: "",
  },
];
