import {JOKER} from '../imagesSlots'

export const dataJoker = [
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
     {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },
    {
        image: JOKER,
        title: "",
        feature: "",
        linkPlay: "#",
        linkDemo: "",
    },  
]