import {SPADEGAMING} from '../imagesSlots'

export const dataSpadeGaming = [
    {
        image: SPADEGAMING.BrothersKingdom,
        title: "BrothersKingdom",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.Roma,
        title: "Roma",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.CaiShenMaxWays,
        title: "Caishen",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.RoyalKatt,
        title: "Royal Katt",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.RoyaleHouse,
        title: "Royale House",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.TigerDanceMaxWays,
        title: "Tiger Dance",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.SpaceConquest,
        title: "Space Conquest",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.RichCaiShen,
        title: "Rich Caishen",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.FierySevens,
        title: "FierySevens",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.FierySevensExclusive,
        title: "Fiery Sevens Exclusive",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.WildWetWin,
        title: "Wild Wet Win",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GoldenLotus,
        title: "Golden Lotus SE",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.PokerWays,
        title: "Poker Ways",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.LuckyKoiExclusice,
        title: "Lucky Koi Exclusice",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.Zeus,
        title: "Zeus",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.EightX3,
        title: "888",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.FiveFortuneDragon,
        title: "5 Fortune Dragon",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.MuayThaiFightor,
        title: "Muay Thai Fighter",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GoldRushCowBoys,
        title: "Gold Rush Cow Boys",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.SexyVegas,
        title: "Sexy Vegas",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.LuckyKoi,
        title: "Lucky Koi",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.DancingFever,
        title: "Dancing Fever",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.JokerTreasureExclusive,
        title: "Joker Treasure Exclusive",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.PrincessWang,
        title: "Princess Wang",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.SugarBonaza,
        title: "Sugar Bonaza",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GoldPanther1,
        title: "Gold Panther",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.CaiShen888,
        title: "Cai Shen 888",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.FirstLove,
        title: "First Love",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.MayanGems,
        title: "Mayan Gems",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.BookOfMyth,
        title: "Book of Myth",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.LegendaryBeasts,
        title: "Legendary Beasts Saga",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.FruitsMania,
        title: "Fruits Mania",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GoldPanther2,
        title: "Gold Panther Maxway",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.CandyCandy,
        title: "Candy Candy",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.ThaiHiLo,
        title: "Thai Hi Lo",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.RubyHood,
        title: "Ruby Hood",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.LoveIdol,
        title: "Love Idol",
        feature: "new",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.Pokdeng,
        title: "Pok Deng",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.PineapplePoker,
        title: "Pineapple Poker",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.CrazyBomber,
        title: "Crazy Bomber",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.DragonEmpire,
        title: "DragonEmpire",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.DoubleFlameBlazing,
        title: "Double Flame",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.HugonQuest,
        title: "Hugon Quest",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.JokerTreasure,
        title: "Joker's Treasure",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.KungfuDragonMaxWays,
        title: "Kungfu Dragon",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.ThreeLuckyStarts,
        title: "Three Lucky Starts",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.MoodieFoodie,
        title: "Moodie Foodie",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.Mega7,
        title: "Mega 7",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.MagicKitty,
        title: "Magic Kitty",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.MoneyMouse,
        title: "Money Mouse",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.RiseOfWereWolves,
        title: "Rise of Werewolves",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.Heroes,
        title: "Heroes",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.FaFaFa,
        title: "Fafafa",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.MagicalLamp,
        title: "Magical Lamp",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.SweetBakery,
        title: "Sweet Bakery",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.TriplePanda,
        title: "Triple Panda",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.HoyeahMonkey,
        title: "Ho Yeah Monkey",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.FaFaFa2,
        title: "FaFaFa2",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GoldenMonkey,
        title: "Golden Monkey",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.JungleKing,
        title: "Jungle King",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.OneSixEightFortunes,
        title: "168 Fortunes",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.WowProsperity,
        title: "Wow Prosperity",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GoldenChicken,
        title: "Golden Chicken",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.BabyCaiShen,
        title: "Baby Cai Shen",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GangsterAxe,
        title: "Gangster Axe",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.CaiYuanGuangJin,
        title: "Cai Yuan Guang Jin",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.DaFuXiaoFu,
        title: "Da Fu Xiao Fu",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.PanFairy,
        title: "Pan Fairy",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.HighWayFortune,
        title: "High Way Fortune",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.BigProsperityStandAlone,
        title: "Big Prosperity SA",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.PokemonGo,
        title: "Pocket Mon Go",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.TigerWarrior,
        title: "Tiger Warrior",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.PirateKing,
        title: "Pirate King",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.DoubleFortunes,
        title: "Double Fortunes",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GoldenWhale,
        title: "Golden Whale",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GolfChampions,
        title: "Golf Champions",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.SeaEmperor,
        title: "Sea Emperor",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.Shanghai008,
        title: "ShangHai 008",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.LuckyCaiShen,
        title: "Lucky Cai Shen",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.HoneyHunter,
        title: "Honey Hunter",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.FestiveLion,
        title: "Festive Lion",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.DrunkenJungle,
        title: "Drunken Jungle",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.AliBaBa,
        title: "Alibaba",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.FamerFather,
        title: "Daddys Vacation",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.FistOfGold,
        title: "Fist of Gold",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.EmperorGateStandAlone,
        title: "Emperor Gate SA",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.ChuTycoon,
        title: "Mr Chu Tycoon",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.ProsperityGods,
        title: "Prosperity Gods",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.CandyPop,
        title: "Candy Pop",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GoldenFist,
        title: "Golden Fist",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.RobStart,
        title: "Rob Start",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.DerbyNight,
        title: "Derby Night",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.AnimalParadise,
        title: "Animal Paradise",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.BicycleRace,
        title: "Bicycle Race",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.DirtBike,
        title: "Dirt Bike",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.ThreeKingDom,
        title: "3 Kingdom The Dragon Boat",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.DogRacing,
        title: "Dog Racing",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.DerbyExpress,
        title: "Derby Express",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GoldenJourney,
        title: "Golden Journey",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GoblinTreasure,
        title: "Goblin Treasure",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.MagicJourney,
        title: "Magic Journey",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.PinballFortune,
        title: "Pinball Fortune",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.TheDragonClan,
        title: "Dragon Clan",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.ShinobiHamster,
        title: "Shinobi Hamster",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.BelangKai,
        title: "Belangkai",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.DragonTiger,
        title: "Dragon Tiger",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.SantanGifts,
        title: "Santa Gifts",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.DragonGoldStandAlone,
        title: "Dragon Gold SA",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GreatStartsStandAlone,
        title: "Great Starts SA",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.IceLandStandAlone,
        title: "Iceland SA",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.LuckyFengShui,
        title: "Lucky Feng Shui",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.WongChoyStandAlone,
        title: "Wong Choy SA",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.FiveFortuneStandAlone,
        title: "5 Fortune SA",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.KingPharaoh,
        title: "King Pharaoh",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.Mermaid,
        title: "Mermaid",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.WongPo,
        title: "Wong Po",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.SupperUltimate,
        title: "Super 8 Ways Ultimate",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GodsKitchen,
        title: "Gods Kitchen",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.IceLand,
        title: "Adventure IceLand",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.LuckyBaby,
        title: "Lucky Baby",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.LuckyMeow,
        title: "Lucky Meow",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.AmazingThaiLand,
        title: "Amazing Thailand",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.DragonGold,
        title: "Dragon Gold",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.EmperorGate,
        title: "Emperor Gate",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.BigProsperity,
        title: "Big Prosperity",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.GreatStarts,
        title: "Great Starts",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.LuckyStrike,
        title: "Lucky Strike",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.RailWay,
        title: "Railway King",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.SpinsStone,
        title: "Spin Stone",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.WongChoy,
        title: "Wong Choy",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.FiveFortune,
        title: "5 Fortune",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
    {
        image: SPADEGAMING.MasterChef,
        title: "Master Chef",
        feature: "",
        linkPlay: "#",
        linkDemo: "#",
    },
]