const images = {
    tick: require("~/assets/images/home/tick.svg").default,
    gamming: require("~/assets/images/home/logo_gaming_curacao.svg").default,
    // licenseimage
    bmm: require("~/assets/images/home/logo_bmm.svg").default,
    itech: require("~/assets/images/home/logo_itechlab.svg").default,
    GLI: require("~/assets/images/home/logo_GLI.svg").default,
    TST: require("~/assets/images/home/logo_TST.svg").default,
    godaddy: require("~/assets/images/home/logo_godaddy.svg").default,
    // licenseimage end

    // guard
    iovation: require("~/assets/images/home/logo_iovation.svg").default,
    threatmetrix: require("~/assets/images/home/logo_threatmetrix.svg").default,
    // guard

    // follow
    facebook: require("~/assets/images/home/fb-icon.svg").default,
    youtube: require("~/assets/images/home/youtube-icon.svg").default,
    // follow

    // payments
    ustd: require("~/assets/images/home/USDT-icon.svg").default,
    bitcoin: require("~/assets/images/home/bitcoin-icon.svg").default,
    ethereum: require("~/assets/images/home/ethereum-icon.svg").default,
    bank: require("~/assets/images/home/bank-icon.svg").default,
    eaziepay: require("~/assets/images/home/logo_eaziepay.svg").default,
    help2pay: require("~/assets/images/home/logo_help2pay.svg").default,
    momo: require("~/assets/images/home/logo_momo.svg").default,
    zalo: require("~/assets/images/home/zalo-icon.svg").default,
    viettlepay: require("~/assets/images/home/viettelpay-icon.svg").default,
    mobifone: require("~/assets/images/home/logo_mobifone.svg").default,
    viettle: require("~/assets/images/home/viettel-icon.svg").default,
    vinaphone: require("~/assets/images/home/logo_vinaphone.svg").default,
    // payments

    // play
    icon18: require("~/assets/images/home/18-icon.svg").default,
    gamecare: require("~/assets/images/home/logo_gamcare.svg").default,
    BGA: require("~/assets/images/home/logo_BGA.svg").default,
    // play

    // language
    smallicon18: require("~/assets/images/home/18-small-icon.svg").default, 
    vietnam: require("~/assets/images/home/logo_vn.jpg"),
    // language

    logo: require("~/assets/images/global/logo.jpeg"),
    desktop: require("~/assets/images/home/desktop_logo.png"),
    //Promos
    imgcard: require("~/assets/images/img-promos/sporttip17.jpg"),
    imgcard1: require("~/assets/images/img-promos/sporttip2.jpg"),
    imgcard2: require("~/assets/images/img-promos/sporttip16.jpg"),
    imgcard3: require("~/assets/images/img-promos/sporttip12.jpg"),
    imgcard4: require("~/assets/images/img-promos/sporttip18.jpg"),
    imgcard5: require("~/assets/images/img-promos/sporttip9.jpg"),
    imgcard6: require("~/assets/images/img-promos/sporttip8.jpg"),
    imgcard7: require("~/assets/images/img-promos/sporttip15.jpg"),
    imgcard8: require("~/assets/images/img-promos/sporttip7.jpg"),
    imgcard9: require("~/assets/images/img-promos/sporttip14.jpg"),
    imgcard10: require("~/assets/images/img-promos/sporttip5.jpg"),
    imgcard11: require("~/assets/images/img-promos/sporttip.jpg"),
    imgcard12: require("~/assets/images/img-promos/sporttip13.jpg"),
    imgcard13: require("~/assets/images/img-promos/sporttip4.jpg"),
    imgcard14: require("~/assets/images/img-promos/sporttip12.jpg"),
    imgcard15: require("~/assets/images/img-promos/sporttip11.jpg"),
    imgcard16: require("~/assets/images/img-promos/sporttip6.jpg"),
    imgcard17: require("~/assets/images/img-promos/sporttip10.jpg"),
    imgcard18: require("~/assets/images/img-promos/sporttip3.jpg"),
    imgcard19: require("~/assets/images/img-promos/sporttip1.jpg"),
    //VIP
    imgbanner: require("~/assets/images/img-vip/banner2.jpg"),
    imgbanner1: require("~/assets/images/img-vip/banner.jpg"),
    imgbanner2: require("~/assets/images/img-vip/banner1.jpg"),
    imgbanner3: require("~/assets/images/img-vip/banner3.jpg"),

    //Sponsors
    imgitems: require("~/assets/images/img-sponsors/Huddersfield-main.jpg"),
    imgitems1: require("~/assets/images/img-sponsors/Huddersfield-1.jpg"),
    imgitems2: require("~/assets/images/img-sponsors/Huddersfield-2.jpg"),
    imgitems3: require("~/assets/images/img-sponsors/Huddersfield-3.jpg"),
    imgitems4: require("~/assets/images/img-sponsors/Huddersfield-4.jpg"),
    imgitems5: require("~/assets/images/img-sponsors/Huddersfield-5.jpg"),
    imgitems6: require("~/assets/images/img-sponsors/Kelly-main.jpg"),
    imgitems7: require("~/assets/images/img-sponsors/Kelly-1.jpg"),
    imgitems8: require("~/assets/images/img-sponsors/Kelly-2.jpg"),
    imgitems9: require("~/assets/images/img-sponsors/Kelly-3.jpg"),
    imgitems10: require("~/assets/images/img-sponsors/Kelly-4.jpg"),
    imgitems11: require("~/assets/images/img-sponsors/Kelly-5.jpg"),
    imgitems12: require("~/assets/images/img-sponsors/LaLiga-main.jpg"),
    imgitems13: require("~/assets/images/img-sponsors/LaLiga-1.jpg"),
    imgitems14: require("~/assets/images/img-sponsors/LaLiga-2.jpg"),
    imgitems15: require("~/assets/images/img-sponsors/LaLiga-3.jpg"),
    imgitems16: require("~/assets/images/img-sponsors/LaLiga-4.jpg"),
    imgitems17: require("~/assets/images/img-sponsors/LaLiga-5.jpg"),
    imgitems18: require("~/assets/images/img-sponsors/RVP-main.jpg"),
    imgitems19: require("~/assets/images/img-sponsors/RVP-1.jpg"),
    imgitems20: require("~/assets/images/img-sponsors/RVP-2.jpg"),
    imgitems21: require("~/assets/images/img-sponsors/RVP-3.jpg"),
    imgitems22: require("~/assets/images/img-sponsors/RVP-4.jpg"),
    imgitems23: require("~/assets/images/img-sponsors/RVP-5.jpg"),
    imgitems24: require("~/assets/images/img-sponsors/DBR-main.jpg"),
    imgitems25: require("~/assets/images/img-sponsors/DBR-1.jpg"),
    imgitems26: require("~/assets/images/img-sponsors/DBR-2.jpg"),
    imgitems27: require("~/assets/images/img-sponsors/DBR-3.jpg"),
    imgitems28: require("~/assets/images/img-sponsors/DBR-4.jpg"),
    imgitems29: require("~/assets/images/img-sponsors/DBR-5.jpg"),
    imgitems30: require("~/assets/images/img-sponsors/JT-main.jpg"),
    imgitems31: require("~/assets/images/img-sponsors/JT-1.jpg"),
    imgitems32: require("~/assets/images/img-sponsors/JT-2.jpg"),
    imgitems33: require("~/assets/images/img-sponsors/JT-3.jpg"),
    imgitems34: require("~/assets/images/img-sponsors/JT-4.jpg"),
    imgitems35: require("~/assets/images/img-sponsors/JT-5.jpg"),
    imgitems36: require("~/assets/images/img-sponsors/BK8-RVP-main.jpg"),
    imgitems37: require("~/assets/images/img-sponsors/BK8-RVP-MYR.jpg"),
    imgitems38: require("~/assets/images/img-sponsors/BK8-RVP-IDR.jpg"),
    imgitems39: require("~/assets/images/img-sponsors/BK8-RVP-THB.jpg"),
    imgitems40: require("~/assets/images/img-sponsors/BK8-RVP-VND.jpg"),
    imgitems41: require("~/assets/images/img-sponsors/bk8cup-main.jpg"),
    imgitems42: require("~/assets/images/img-sponsors/bk8cup-1.jpg"),
    imgitems43: require("~/assets/images/img-sponsors/bk8cup-2.jpg"),
    imgitems44: require("~/assets/images/img-sponsors/bk8cup-3.jpg"),
    imgitems45: require("~/assets/images/img-sponsors/bk8cup-4.jpg"),
    imgitems46: require("~/assets/images/img-sponsors/honda-main.jpg"),
    imgitems47: require("~/assets/images/img-sponsors/honda-1.jpg"),
    imgitems48: require("~/assets/images/img-sponsors/honda-2.jpg"),
    imgitems49: require("~/assets/images/img-sponsors/honda-4.jpg"),
    imgitems50: require("~/assets/images/img-sponsors/METP-main.jpg"),
    imgitems51: require("~/assets/images/img-sponsors/METP-1.jpg"),
    imgitems52: require("~/assets/images/img-sponsors/METP-2.jpg"),
    imgitems53: require("~/assets/images/img-sponsors/METP-3.jpg"),
    imgitems54: require("~/assets/images/img-sponsors/METP-4.jpg"),

    
    // banner
    banner1: require("~/assets/images/home/banner_slider_1.jpg"),
    banner2: require("~/assets/images/home/banner_slider_2.jpg"),
    banner3: require("~/assets/images/home/banner_slider_3.jpg"),
    banner4: require("~/assets/images/home/banner_slider_4.jpg"),
    banner5: require("~/assets/images/home/banner_slider_5.jpg"),
    banner6: require("~/assets/images/home/banner_slider_6.jpg"),
    // banner

    // football
    hudder: require("~/assets/images/home/logo_hudderfile.png"),
    valencia: require("~/assets/images/home/logo_valencia.png"),
    athletic: require("~/assets/images/home/logo_athletic.png"),
    villarreal: require("~/assets/images/home/logo_villarreal.png"),
    elche: require("~/assets/images/home/logo_elche.png"),
    mallorca: require("~/assets/images/home/logo_mallorca.png"),
    // football

    //image-list-item-game
    ForturnStarts: require('~/assets/images/img-slot/list-slots/nextspin/list-slots-5-fortune-starts.jpg'),
    SevenDragons: require('~/assets/images/img-slot/list-slots/nextspin/list-slots-7-dragons.jpg'),
    BuffaloKing: require('~/assets/images/img-slot/list-slots/nextspin/list-slots-buffalo-king.jpg'),
    CandyBonanzaXmas: require('~/assets/images/img-slot/list-slots/nextspin/list-slots-candy-bonanza-xmas.jpg'),
    CandyBonanza: require('~/assets/images/img-slot/list-slots/nextspin/list-slots-candy-bonanza.jpg'),
    ClassicFruits: require('~/assets/images/img-slot/list-slots/nextspin/list-slots-classic-fruits.jpg'),

    //image-banner-list-item
    BannerInItem: require('~/assets/images/banner-biggest-and-most-trusted-slots.jpg'),

    //header
    arrowTippy: require('~/assets/images/global/arrowTippy.svg').default,
    ranking1: require('~/assets/images/global/ranking1.png'),
    userNormal: require('~/assets/images/global/user-normal.png'),
    plus: require('~/assets/images/global/plus.png'),
    iconCollapse: require('~/assets/images/global/icon-collapse.png'),
    national: require('~/assets/images/global/national.png'),
    malaysia: require('~/assets/images/global/malaysia.png'),
    error: require('~/assets/images/global/error.png'),
    success: require('~/assets/images/global/success.png'),

    //sidebar
    sidebarLeft: require('~/assets/images/sidebar/sl-download.jpg'),
    sidebarRight: require('~/assets/images/sidebar/sr-contact.jpg'),
    //sidebar mobile
    smbContact: require('~/assets/images/sidebarmobile/icon_contact.png'),
    smbDesktop: require('~/assets/images/sidebarmobile/icon_desktop.png'),
    smbAbout: require('~/assets/images/sidebarmobile/icon_menu_about.png'),
    smbDownload: require('~/assets/images/sidebarmobile/icon_menu_download.png'),
    smbLeaderBoard: require('~/assets/images/sidebarmobile/icon_menu_leaderboard.png'),
    smbSponsor: require('~/assets/images/sidebarmobile/icon_menu_sponsor.png'),
    smbMenu: require('~/assets/images/sidebarmobile/icon_menu_tnc.png'),
    smbPromotion: require('~/assets/images/sidebarmobile/icon_promotion_big.png'),
    smbProgram: require('~/assets/images/sidebarmobile/icon_referral_program.png'),
    smbVip: require('~/assets/images/sidebarmobile/icon_vip_big.png'),
    smbLogo: require('~/assets/images/sidebarmobile/logosidebar.jpg'),
    smbHome: require('~/assets/images/sidebarmobile/icon_home_big.png'),
    smbLogout: require('~/assets/images/sidebarmobile/icon_logout.png'),
    //navbar
    homeIcon: require('~/assets/images/navbar/home.jpg'),
    homeHoverIcon: require('~/assets/images/navbar/home-on.jpg'),
    mobileIcon: require('~/assets/images/navbar/mobile.jpg'),
    mobileHoverIcon: require('~/assets/images/navbar/mobile-on.jpg'),
    subNew: require('~/assets/images/navbar/new_icon.png'),
    subHot: require('~/assets/images/navbar/hot_icon.png'),
    navNew: require('~/assets/images/navbar/bk8-new-icon.gif'),
    navWin: require('~/assets/images/navbar/bk8-win-icon.gif'),
    //sub navbar
    sub11: require('~/assets/images/navbar/11.png'),
    sub12: require('~/assets/images/navbar/12.png'),
    sub13: require('~/assets/images/navbar/13.png'),
    sub21: require('~/assets/images/navbar/21.jpg'),
    sub31: require('~/assets/images/navbar/31.png'),
    sub32: require('~/assets/images/navbar/32.png'),
    sub33: require('~/assets/images/navbar/33.png'),
    sub31h: require('~/assets/images/navbar/31h.png'),
    sub32h: require('~/assets/images/navbar/32h.png'),
    sub33h: require('~/assets/images/navbar/33h.png'),
    sub41: require('~/assets/images/navbar/41.png'),
    sub42: require('~/assets/images/navbar/42.png'),
    sub41h: require('~/assets/images/navbar/41h.png'),
    sub42h: require('~/assets/images/navbar/42h.png'),
    sub51: require('~/assets/images/navbar/51.png'),
    sub52: require('~/assets/images/navbar/52.png'),
    sub53: require('~/assets/images/navbar/53.png'),
    sub54: require('~/assets/images/navbar/54.png'),
    sub51h: require('~/assets/images/navbar/51h.png'),
    sub52h: require('~/assets/images/navbar/52h.png'),
    sub55: require('~/assets/images/navbar/55.png'),
    sub56: require('~/assets/images/navbar/56.png'),
    sub57: require('~/assets/images/navbar/57.png'),
    sub57h: require('~/assets/images/navbar/57h.png'),
    sub58: require('~/assets/images/navbar/58.png'),
    sub59: require('~/assets/images/navbar/59.png'),
    sub510: require('~/assets/images/navbar/510.png'),
    sub511: require('~/assets/images/navbar/511.png'),
    sub512: require('~/assets/images/navbar/512.png'),
    sub61: require('~/assets/images/navbar/61.png'),
    sub62: require('~/assets/images/navbar/62.png'),
    sub63: require('~/assets/images/navbar/63.png'),
    sub64: require('~/assets/images/navbar/64.png'),
    sub65: require('~/assets/images/navbar/65.png'),
    sub66: require('~/assets/images/navbar/66.png'),
    sub67: require('~/assets/images/navbar/67.png'),
    sub68: require('~/assets/images/navbar/68.png'),
    sub69: require('~/assets/images/navbar/69.png'),
    sub610: require('~/assets/images/navbar/610.png'),
    sub611: require('~/assets/images/navbar/611.png'),
    sub612: require('~/assets/images/navbar/612.png'),
    sub613: require('~/assets/images/navbar/613.png'),
    sub614: require('~/assets/images/navbar/614.png'),
    sub615: require('~/assets/images/navbar/615.png'),
    sub61h: require('~/assets/images/navbar/61h.png'),
    sub71: require('~/assets/images/navbar/71.png'),
    sub72: require('~/assets/images/navbar/72.png'),
    sub73: require('~/assets/images/navbar/73.png'),
    sub74: require('~/assets/images/navbar/74.png'),
    sub75: require('~/assets/images/navbar/75.png'),
    sub76: require('~/assets/images/navbar/76.png'),
    sub77: require('~/assets/images/navbar/77.png'),
    sub78: require('~/assets/images/navbar/78.png'),
    sub79: require('~/assets/images/navbar/79.png'),
    sub710: require('~/assets/images/navbar/710.png'),
    sub711: require('~/assets/images/navbar/711.png'),
    sub712: require('~/assets/images/navbar/712.png'),
    sub71h: require('~/assets/images/navbar/71h.png'),
    sub72h: require('~/assets/images/navbar/72h.png'),
    sub73h: require('~/assets/images/navbar/73h.png'),
    sub74h: require('~/assets/images/navbar/74h.png'),
    sub75h: require('~/assets/images/navbar/75h.png'),
    sub77h: require('~/assets/images/navbar/77h.png'),
    sub78h: require('~/assets/images/navbar/78h.png'),
    sub79h: require('~/assets/images/navbar/79h.png'),
    sub710h: require('~/assets/images/navbar/710h.png'),
    sub81: require('~/assets/images/navbar/81.png'),
    sub82: require('~/assets/images/navbar/82.png'),
    sub83: require('~/assets/images/navbar/83.png'),
    sub81h: require('~/assets/images/navbar/81h.png'),
    sub82h: require('~/assets/images/navbar/82h.png'),
    sub91: require('../assets/images/img-lottery/firms_lottery_subbutton_super_over.png'),
    sub92: require('../assets/images/img-lottery/firms_lottery_subbutton_9k_over.png'),
    sub93: require('~/assets/images/navbar/93.png'),
    sub92h: require('~/assets/images/navbar/92h.png'),
    sub93h: require('~/assets/images/navbar/93h.png'),
    sub121: require('~/assets/images/navbar/121.png'),
    sub111: require('~/assets/images/navbar/111.png'),
    sub112: require('~/assets/images/navbar/112.png'),
    sub113: require('~/assets/images/navbar/113.png'),
    sub114: require('~/assets/images/navbar/114.png'),
    sub111h: require('~/assets/images/navbar/111h.png'),
    sub112h: require('~/assets/images/navbar/112h.png'),
    sub113h: require('~/assets/images/navbar/113h.png'),
    sub114h: require('~/assets/images/navbar/114h.png'),
    sub115: require('~/assets/images/navbar/115.png'),
    sub116: require('~/assets/images/navbar/116.png'),
    sub117: require('~/assets/images/navbar/117.png'),
    sub118: require('~/assets/images/navbar/118.png'),
    sub119: require('~/assets/images/navbar/119.png'),
    sub1110: require('~/assets/images/navbar/1110.png'),

    // video
    video: require('~/assets/images/home/video-desr.png'),
    matches:require('~/assets/images/home/Upcoming_match_banner.jpg'),
    baccarat:require('~/assets/images/home/baccarat.jpg'),
    baccarat1:require('~/assets/images/home/Baccarat1.png'),
    baccarat2:require('~/assets/images/home/Baccarat2.png'),
    baccarat3:require('~/assets/images/home/Baccarat3.png'),

    // hot game
    bannerStrimuky: require('~/assets/images/home/games_banner_sTriMnky.jpg'),
    trimnky:require('~/assets/images/home/game_sTriMnky.jpg'),
    sweetLava:require('~/assets/images/home/game_sSweetLava.jpg'),
    dragon:require('~/assets/images/home/game_sDrgBlitz.jpg'),
    monkey:require('~/assets/images/home/game_aMnkyJump.jpg'),
    shake:require('~/assets/images/home/game_sShkBoomX2.jpg'),
    bigpro:require('~/assets/images/home/game_bigpro.jpg'),
    three:require('~/assets/images/home/game_threeLucky.jpg'),
    firstLove:require('~/assets/images/home/game_firstlove.jpg'),
    legendery:require('~/assets/images/home/game_legendaryBeasts.jpg'),
    fiery:require('~/assets/images/home/game_Fierysevens.jpg'),
    gameIcon:require('~/assets/images/home/icons_NS_logo.png'),
    gameIcons:require('~/assets/images/home/icons_SG_logo.png'),

    // sport 
    esp1: require('~/assets/images/home/esp_1.jpg'),
    esp2: require('~/assets/images/home/esp_2.jpg'),
    esp3: require('~/assets/images/home/esp_3.jpg'),
    esp4: require('~/assets/images/home/esp_4.jpg'),
    esp5: require('~/assets/images/home/esp_5.jpg'),
    esp6: require('~/assets/images/home/esp_6.jpg'),
    esp7: require('~/assets/images/home/esp_7.jpg'),
    esp8: require('~/assets/images/home/esp_8.jpg'),
    esp9: require('~/assets/images/home/esp_9.jpg'),
    esp10: require('~/assets/images/home/esp_10.jpg'),

    // dowload
    dowload1: require('~/assets/images/home/dowload_app_1.png'),
    dowload2: require('~/assets/images/home/dowload_app_2.png'),
    dowload3: require('~/assets/images/home/dowload_app_3.png'),
    dowload4: require('~/assets/images/home/dowload_app_4.png'),
    qrApp: require('~/assets/images/home/qr-code-ios-new.png'),
    qrAdroid: require('~/assets/images/home/qr-code-android-new.png'),
    //chat button
    chatBtn: require('~/assets/images/global/chat-button.svg').default,
    
    //register
    rWelcome: require('~/assets/images/register/bk8_welcome_VI_VN.jpg'),
    bgRegister: require('~/assets/images/register/bk8-web-register.jpg'),
    rSpan: require('~/assets/images/register/span.jpg'),
    rBanner1: require('~/assets/images/register/banner1.jpg'),
    rBanner2: require('~/assets/images/register/banner2.jpg'),
    rCollapse: require('~/assets/images/register/collapse.png'),
    rBack: require('~/assets/images/register/rBack.png'),

    //deposit
    // fastBank: require('~/assets/images/img-member/img-deposit/fastbank.jpg'),
    // banktranfer: require('~/assets/images/img-member/img-deposit/bank_transfer_gray.png'),
    // h2p: require('~/assets/images/img-member/img-deposit/H2P_gray.png'),
    // eWallet: require('~/assets/images/img-member/img-deposit/download.jpg'),
    // varderPay: require('~/assets/images/img-member/img-deposit/VDP_ori.png'),
    // crypto: require('~/assets/images/img-member/img-deposit/CRYPTOPAY_gray.png'),
    // fPay: require('~/assets/images/img-member/img-deposit/FP_gray.png'),

    //withdraw
    banktranfer: require('~/assets/images/img-member/img-withdraw/bank_transfer_gray.png'),
    banktranfer1: require('~/assets/images/img-member/img-withdraw/bank_transfer_ori.png'),
    crypto: require('~/assets/images/img-member/img-withdraw/CRYPTOPAY_gray.png'),
    crypto1: require('~/assets/images/img-member/img-withdraw/CRYPTOPAY_ori.png'),
    terra: require('~/assets/images/img-member/img-withdraw/terra.png'),

    //trans
    transfer: require('~/assets/images/img-member/img-tranfer/tContent_transferContent_interchangeIcon.png'),
    side: require('~/assets/images/img-member/img-tranfer/sidePanel_transfer.png'),

    promostion1: require('~/assets/images/home/promostion1.jpg'),
    promostion2: require('~/assets/images/home/promostion2.jpg'),
    promostion3: require('~/assets/images/home/promostion3.jpg'),
    promostion4: require('~/assets/images/home/promostion4.jpg'),


    bh1: require('~/assets/images/home/bh1.jpg'),
    bh2: require('~/assets/images/home/bh2.jpg'),
    bh3: require('~/assets/images/home/bh3.jpg'),
    bh4: require('~/assets/images/home/bh4.jpg'),
    bh5: require('~/assets/images/home/bh5.jpg'),

    //Sport
    IBC: require("~/assets/images/navbar/31.png"),
    CMD: require("~/assets/images/navbar/32.png"),

    //esport
    IM: require("~/assets/images/navbar/41.png"),
    LH: require("~/assets/images/navbar/42.png"),

    //lottery
    SPLT: require("../assets/images/img-lottery/super.jpg"),
    NK: require("~/assets/images/img-lottery/9k.jpg"),

    //casio
    SX: require("~/assets/images/img-casino/list-casino-ae-casino.jpg"),
    DG: require("~/assets/images/img-casino/list-casino-dream-gaming.jpg"),
    EVO: require("~/assets/images/img-casino/list-casino-evalution-gaming.jpg"),
    BG: require("~/assets/images/img-casino/list-casino-big-gaming.jpg"),
    WM: require("~/assets/images/img-casino/list-casino-wm-casino.jpg"),
    GPI: require("~/assets/images/img-casino/list-casino-gameplay-casino.jpg"),
    AG: require("~/assets/images/img-casino/casino_ag.jpg"),
    EB: require("~/assets/images/img-casino/list-casino-ebet-casino.jpg"),
    PT: require("~/assets/images/img-casino/list-casino-playtech.jpg"),
    SA: require("~/assets/images/img-casino/list-casino-sa-gaming.jpg"),
    PP:  require("~/assets/images/img-casino/list-casino-pragmatic-play.jpg"),
    AB: require("~/assets/images/img-casino/list-casino-allbest-casino.jpg"),

    //Slider Casino
    Attrative: require("~/assets/images/img-casino/banner/banner-casino-attrative.jpg"),
    EnjoyUnlimated: require("~/assets/images/img-casino/banner/banner-casino-enjoy-unlimated.jpg"),
    BiggestAndMost: require("~/assets/images/img-casino/inner-slide-biggest-and-most.jpg")
}

export default images;