import images from '~/constants/images'

export const data = [
    {
        id: 1,
        img: images.homeIcon,
        imgHover: images.homeHoverIcon,
        url: '/',
        subData: [
            {
                id: 1,
                img: images.sub11,
                label: 'Info Centre',
                url: '/faq',
            },
            {
                id: 2,
                img: images.sub12,
                label: 'About Us',
                url: '/about-us',
            },
            {
                id: 3,
                img: images.sub13,
                label: 'Contact Us',
                url: '/contact-us'
            },
        ]
    },
    {
        id: 2,
        img: images.mobileIcon,
        imgHover: images.mobileHoverIcon,
        url: '/mobile',
        subData: [
            {
                id: 1,
                img: images.sub21,
                label: '',
                url: '/mobile'
            },
        ]
    },
    {
        id: 3,
        label: 'Thể Thao',
        url: '/sports',
        subData: [
            {
                id: 1,
                img: images.sub31,
                imgHover: images.sub31h,
                label: 'IBC/MAXBET/SABA',
                code: 'IBC',
                url: '/sports',
                type: 'SB',
            },
            {
                id: 2,
                img: images.sub32,
                imgHover: images.sub32h,
                label: 'CMD365',
                code: 'CMD',
                url: '/sports',
                type: 'SB',
            }
        ]
    },
    {
        id: 4,
        label: 'E-Sports',
        url: '/esports',
        subData: [
            {
                id: 1,
                img: images.sub41,
                imgHover: images.sub41h,
                label: 'IM Esports',
                code: 'IM',
                url: '/esports',
                type:'ES',
            },
            {
                id: 2,
                img: images.sub42,
                imgHover: images.sub42h,
                label: 'TF-Gaming',
                code: 'LH',
                url: '/esports',
                type:'ES',
            },
        ]
    },
    {
        id: 5,
        label: 'đánh bài',
        url: '/casino',
        subData: [
            {
                id: 1,
                img: images.sub51,
                imgHover: images.sub51h,
                label: 'AE Casino',
                code: 'SX',
                url: '/casino',
                type: 'LC',
            },
            {
                id: 2,
                img: images.sub52,
                imgHover: images.sub52h,
                label: 'Dream Gaming',
                code: 'DG',
                url: '/casino',
                type: 'LC',
            },
            {
                id: 3,
                img: images.sub53,
                label: 'Evolution Gaming',
                code: 'EVO',
                url: '/casino',
                type: 'LC',
            },
            {
                id: 4,
                img: images.sub54,
                label: 'Big Gaming',
                code: 'BG',
                url: '/casino',
                type: 'LC',
            },
            {
                id: 5,
                img: images.sub55,
                label: 'WM Casino',
                code: 'WM',
                url: '/casino',
                type: 'LC',
            },
            {
                id: 6,
                img: images.sub56,
                label: 'Game Play',
                code: 'GPI',
                url: '/casino',
                type: 'LC',
            },
            {
                id: 7,
                img: images.sub57,
                label: 'Asia Gaming',
                code: 'AG',
                url: '/casino',
                type: 'LC',
            },
            {
                id: 8,
                img: images.sub58,
                label: 'Microgaming',
                code: 'MG',
                url: '/casino',
                type: 'LC',
            },
            {
                id: 9,
                img: images.sub59,
                label: 'EBET',
                code: 'EB',
                url: '/casino',
                type: 'LC',
            },
            {
                id: 10,
                img: images.sub510,
                label: 'PlayTech',
                code: 'PT',
                url: '/casino',
                type: 'LC',
            },
            {
                id: 11,
                img: images.sub510,
                label: 'SA Gaming',
                code: 'SA',
                url: '/casino',
                type: 'LC',
            },
            {
                id: 12,
                img: images.sub511,
                label: 'Pragmatic Play',
                code: 'PP',
                url: '/casino',
                type: 'LC',
            },
            {
                id: 13,
                img: images.sub512,
                label: 'Allbet',
                code: 'AB',
                url: '/casino',
                type: 'LC',
            },
        ],
    },
    {
        id: 6,
        label: 'Slots',
        url: '/slots',
        subData: [
            {
                id: 1,
                img: images.sub62,
                label: 'Spadegaming',
                code: 'SG',
                url: '/slots',
                type: 'SL',
            },
            {
                id: 2,
                img: images.sub63,
                label: 'JiLi',
                code: 'SXJL',
                url: '/slots',
                type: 'SL',
            },
            {
                id: 3,
                img: images.sub65,
                label: 'Microgaming',
                code: 'MG',
                url: '/slots',
                type: 'SL',
            },
            {
                id: 4,
                img: images.sub68,
                label: 'JOKER',
                code: 'JK',
                url: '/slots',
                type: 'SL',
            },
            {
                id: 5,
                img: images.sub68,
                label: 'PlayTech',
                code: 'PT',
                url: '/slots',
                type: 'SL',
            },
            {
                id: 6,
                img: images.sub68,
                label: 'Game Play',
                code: 'GPI',
                url: '/slots',
                type: 'SL',
            },
            {
                id: 7,
                img: images.sub613,
                label: 'Pragmatic Play',
                code: 'PP',
                url: '/slots',
                type: 'SL',
            },
            {
                id: 8,
                img: images.sub614,
                label: 'Red Tiger',
                code: 'SXRT',
                url: '/slots',
                type: 'SL',
            },
        ],
    },
    {
        id: 7,
        label: 'Bắn Cá',
        url: '/fishing',
        subData: [
            {
                id: 1,
                img: images.sub71,
                imgHover: images.sub71h,
                label: 'Spade Gaming',
                code: 'SG',
                url: '/fishing',
                type: 'FH',
            },
            {
                id: 2,
                img: images.sub72,
                imgHover: images.sub72h,
                label: 'JILI',
                code: 'SXJL',
                url: '/fishing',
                type: 'FH',
            },
        ],
    },
    // {
    //     id: 8,
    //     label: '3d games',
    //     url: '/games/kingmaker',
    //     subData: [
    //         {
    //             id: 1,
    //             img: images.sub81,
    //             imgHover: images.sub81h,
    //             label: 'King maker',
    //             url: '/',
    //         },
    //         {
    //             id: 2,
    //             img: images.sub82,
    //             imgHover: images.sub82h,
    //             label: 'Game Play',
    //             url: '/',
    //         },
    //         {
    //             id: 3,
    //             img: images.sub83,
    //             label: 'V8 Poker',
    //             url: '/',
    //         },
    //     ],
    //     new: true
    // },
    {
        id: 9,
        label: 'Xổ Số',
        url: '/lottery',
        subData: [
            {
                id: 1,
                img: images.sub91,
                label: 'SUPER',
                code: 'SPLT',
                url: '/lottery',
                type: 'LT',
            },
            {
                id: 2,
                img: images.sub92,
                //imgHover: images.sub92h,
                label: '9K',
                code: '9K',
                url: '/lottery',
                type: 'LT',
            },
        ],
    },
    {
        id: 10,
        label: 'Khuyến Mãi',
        url: '/promos',
        subData: []
    },
    {
        id: 11,
        label: 'Tài Trợ',
        url: '/sponsors',
        new: true,
        subData: [
            {
                id: 1,
                img: images.sub111,
                imgHover: images.sub111h,
                label: 'Huddersfield Town A.F.C Official Global Partner 2021 / 22',
                url: '/',
            },
            {
                id: 2,
                img: images.sub112,
                imgHover: images.sub112h,
                label: 'Valencia CF Official Asian Betting Partner 2021 / 22',
                url: '/',
            },
            {
                id: 3,
                img: images.sub113,
                imgHover: images.sub113h,
                label: 'Athletic Club Official Asian Betting Partner 2021 /22',
                url: '/',
            },
            {
                id: 4,
                img: images.sub114,
                imgHover: images.sub114h,
                label: 'Villarreal CF Official Asian Betting Partner 2021 / 22',
                url: '/',
            },
            {
                id: 5,
                img: images.sub115,
                label: 'Elche CF Official Asian Betting Partner 2021 /22',
                url: '/',
            },
            {
                id: 6,
                img: images.sub116,
                label: 'RCD Mallorca Town A.F.C Official Asian Partner 2021 / 22',
                url: '/',
            },
            {
                id: 7,
                img: images.sub117,
                label: 'Kelly Smith Ambassador 2021/22 ',
                url: '/',
            },
            {
                id: 8,
                img: images.sub118,
                label: 'Robin Van Persie Ambassador 2019/21',
                url: '/',
            },
            {
                id: 9,
                img: images.sub119,
                label: 'John Terry Ambassador 2018/19',
                url: '/',
            },
            {
                id: 10,
                img: images.sub1110,
                label: 'Sponsors & Events',
                url: '/',
            },
        ],
    },
    {
        id: 12,
        label: 'vip',
        url: '/vip',
        subData: [
            {
                id: 1,
                img: images.sub121,
                label: '',
                url: '/vip'
            },
        ]
    }
]