const routes = {
    home: '/',
    sports: 'sports',
    esports: 'esports',
    casino: 'casino',
    promos:'promos',
    vip:'vip',
    slots: 'slots',
    leaderboard: 'leaderboard',
    sponsors:'sponsors',
    lottery: 'lottery',
    fishing: 'fishing',
    games: 'games',
    register:'register',
    mregister:'mregister',
    forgotPassword:'forgotPassword',
    memberSettings: 'member-settings',
    referProgram: 'm-referral-program',
    aboutUs:'about-us',
    infor: 'tnc',
    banking: 'funds',
    account: 'myaccount',
    download: 'download-bk8-app',
    contact: 'contact',
    login: 'login',
    deposit: 'deposit',
    tranfer: 'tranfer',
    withdraw: 'withdraw',
    history: 'history',
    sponsorship:'msponsorship',
    promosMobile:'mpromos',
    leaderboardMobile: 'mleaderboard',
    vipMobile:'mvip',
    memberprofile: 'memberprofile',
    passwordmobile: 'passwordmobile',
    providerpassword: 'providerpassword',
    inbox: 'inbox',
    referral: 'referral',
    minstantrebate: 'minstantrebate',
    reset: 'reset',
    slotsmobile: 'mslots/:provider_code',
    fishingmobile: 'mfishing/:provider_code',
}


export default routes