import images from "~/constants/images"
export const fetchGames = [
    {
        id:1,
        img: images.trimnky,
        title: "Triple Monkey",
        desc: "by Nextspin",
        logo: images.gameIcon, 
        link: "#",
    },
    {
        id:2,
        img: images.sweetLava,
        title: "Sweet Lava",
        desc: "by Nextspin",
        logo: images.gameIcon, 
        link: "#",
    },
    {
        id:3,
        img: images.dragon,
        title: "Dragon Blitz",
        desc: "by Nextspin",
        logo: images.gameIcon, 
        link: "#",
    },
    {
        id:4,
        img: images.monkey,
        title: "Monkey Jump",
        desc: "by Nextspin",
        logo: images.gameIcon, 
        link: "#",
    },
    {
        id:5,
        img: images.shake,
        title: "Shake Boom Boom",
        desc: "by Nextspin",
        logo: images.gameIcon, 
        link: "#",
    },
    {
        id:6,
        img: images.bigpro,
        title: "Big Prosperity SA",
        desc: "by Nextspin",
        logo: images.gameIcons, 
        link: "#",
    },
    {
        id:7,
        img: images.three,
        title: "Three Lucky Stars",
        desc: "by Nextspin",
        logo: images.gameIcons, 
        link: "#",
    },
    {
        id:8,
        img: images.firstLove,
        title: "First Love",
        desc: "by Nextspin",
        logo: images.gameIcons, 
        link: "#",
    },
    {
        id:9,
        img: images.legendery,
        title: "Legendary Beasts Saga",
        desc: "by Nextspin",
        logo: images.gameIcons, 
        link: "#",
    },
    {
        id:10,
        img: images.fiery,
        title: "Fiery Sevens",
        desc: "by Nextspin",
        logo: images.gameIcons, 
        link: "#",
    },
]


export const fetchSports = [
    {
        id:1,
        img: images.esp1,
        title: "2022-06-4 Pháp bại trận, Bỉ hủy diệt, Áo của Rangnick thắng",
        desc: "Chỉ có ba trận đấu từ League A của UEFA Nations League vào đêm thứ Sáu, nhưng cả ba đều tạo ra những cơn địa chấn khá...",
        more: "Đọc Thêm", 
        link: "/s",
    },
    {
        id:2,
        img: images.esp2,
        title: "2022-06-4 Pháp bại trận, Bỉ hủy diệt, Áo của Rangnick thắng",
        desc: "Chỉ có ba trận đấu từ League A của UEFA Nations League vào đêm thứ Sáu, nhưng cả ba đều tạo ra những cơn địa chấn khá...",
        more: "Đọc Thêm", 
        link: "/s",
    },
    {
        id:3,
        img: images.esp3,
        title: "2022-06-4 Pháp bại trận, Bỉ hủy diệt, Áo của Rangnick thắng",
        desc: "Chỉ có ba trận đấu từ League A của UEFA Nations League vào đêm thứ Sáu, nhưng cả ba đều tạo ra những cơn địa chấn khá...",
        more: "Đọc Thêm", 
        link: "/s",
    },
    {
        id:4,
        img: images.esp4,
        title: "2022-06-4 Pháp bại trận, Bỉ hủy diệt, Áo của Rangnick thắng",
        desc: "Chỉ có ba trận đấu từ League A của UEFA Nations League vào đêm thứ Sáu, nhưng cả ba đều tạo ra những cơn địa chấn khá...",
        more: "Đọc Thêm", 
        link: "/s",
    },
    {
        id:5,
        img: images.esp5,
        title: "2022-06-4 Pháp bại trận, Bỉ hủy diệt, Áo của Rangnick thắng",
        desc: "Chỉ có ba trận đấu từ League A của UEFA Nations League vào đêm thứ Sáu, nhưng cả ba đều tạo ra những cơn địa chấn khá...",
        more: "Đọc Thêm", 
        link: "/s",
    },
    {
        id:6,
        img: images.esp6,
        title: "2022-06-4 Pháp bại trận, Bỉ hủy diệt, Áo của Rangnick thắng",
        desc: "Chỉ có ba trận đấu từ League A của UEFA Nations League vào đêm thứ Sáu, nhưng cả ba đều tạo ra những cơn địa chấn khá...",
        more: "Đọc Thêm", 
        link: "/s",
    },
    {
        id:7,
        img: images.esp7,
        title: "2022-06-4 Pháp bại trận, Bỉ hủy diệt, Áo của Rangnick thắng",
        desc: "Chỉ có ba trận đấu từ League A của UEFA Nations League vào đêm thứ Sáu, nhưng cả ba đều tạo ra những cơn địa chấn khá...",
        more: "Đọc Thêm", 
        link: "/s",
    },
    {
        id:8,
        img: images.esp8,
        title: "2022-06-4 Pháp bại trận, Bỉ hủy diệt, Áo của Rangnick thắng",
        desc: "Chỉ có ba trận đấu từ League A của UEFA Nations League vào đêm thứ Sáu, nhưng cả ba đều tạo ra những cơn địa chấn khá...",
        more: "Đọc Thêm", 
        link: "/s",
    },
    {
        id:9,
        img: images.esp9,
        title: "2022-06-4 Pháp bại trận, Bỉ hủy diệt, Áo của Rangnick thắng",
        desc: "Chỉ có ba trận đấu từ League A của UEFA Nations League vào đêm thứ Sáu, nhưng cả ba đều tạo ra những cơn địa chấn khá...",
        more: "Đọc Thêm", 
        link: "/s",
    },
    {
        id:10,
        img: images.esp10,
        title: "2022-06-4 Pháp bại trận, Bỉ hủy diệt, Áo của Rangnick thắng",
        desc: "Chỉ có ba trận đấu từ League A của UEFA Nations League vào đêm thứ Sáu, nhưng cả ba đều tạo ra những cơn địa chấn khá...",
        more: "Đọc Thêm", 
        link: "/s",
    },
    
]
